'''

Tests for the forward characteristics problem: a net marched against a wall that was given.

The module names its own settling check and this file is it. A truncated ideal contour's wall is a
streamline of a shock-free field, so marching the forward solver over that wall is solving the same
problem the inverse solve already solved, and the inverse solve is verified in
docs/NozzleContourValidation.md. It is a manufactured solution generated by a solver that has
already been checked, and it needs no external reference.

That matters because the forward march is what every family except the truncated ideal contour
relies on for its interior, and until this file existed nothing exercised it. The defect that
prompted these tests was invisible for exactly that reason: it fires on the walls the optimized
families draw and not on the one family whose interior comes from the inverse solve, so the shipped
example never saw it.

'''
import json
import os

import numpy as np
import pytest

from NOVA.characteristics import CharacteristicGas
from NOVA.directCharacteristics import marchPrescribedWall
from NOVA.wallGeometry import PrescribedWall, SampledSegment, raoThroatArc

#--------------------------------------------------------------------------------------------------------------------------#
# -- A truncated ideal contour to march over -- #
#--------------------------------------------------------------------------------------------------------------------------#

@pytest.fixture(scope = 'module')
def truncatedIdeal():

    '''One solved truncated ideal contour, without a jacket, reused by every test here.'''

    from NOVA.Nozzle import Nozzle

    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)
    assetPath = os.path.join(root, 'src', 'NOVA', 'assets', 'NOVANozzle.json')
    with open(assetPath, encoding = 'utf-8') as handle:
        config = json.load(handle)
    config.update({'divergingSectionType': 'tic', 'Lstar': None, 'plumeAmbientPressure': None,
                   'plotsEnabled': False, 'export': False, 'makeCoolingChannels': 'off',
                   'makeInletVolute': 'off', 'makeOutletVolute': 'off',
                   'makeRadiativeExtension': 'off', 'filmCooling': 'off'})

    scratch = os.path.join(root, 'runs', 'testDirectCharacteristics')
    os.makedirs(scratch, exist_ok = True)
    configPath = os.path.join(scratch, 'directTestConfig.json')
    with open(configPath, 'w', encoding = 'utf-8') as handle:
        json.dump(config, handle, indent = 2)

    # Redirecting the output root keeps a solve from writing into the repository. It is a change
    # to the class rather than to an instance, so it is restored whatever happens.
    originalOutputRoot = Nozzle._getOutputRoot
    try:
        Nozzle._getOutputRoot = lambda self, _base = scratch: _base
        nozzle = Nozzle()
        nozzle.generateNozzle(configPath = configPath)
    finally:
        Nozzle._getOutputRoot = originalOutputRoot

    return nozzle

def wallAndStartingLine(nozzle):

    '''

    The contour's own wall as a `PrescribedWall`, and the kernel boundary the march starts from.

    The wall is rebuilt in the two segments the march expects, the throat arc it was launched from
    and the contoured run behind it, so stations on it are comparable with the starting station.
    The starting line is the same slice of the expansion kernel the optimized families take.

    '''

    arcEnd = float(nozzle.throatWallX[-1])
    xWall = np.asarray(nozzle.xNozzleWallDivergingNonDimensional, dtype = float)
    rWall = np.asarray(nozzle.rNozzleWallDivergingNonDimensional, dtype = float)

    beyond = xWall > arcEnd + 1e-9
    contourX = np.concatenate([[arcEnd], xWall[beyond]])
    contourR = np.concatenate([[float(nozzle.throatWallR[-1])], rWall[beyond]])
    advancing = np.concatenate([[True], np.diff(contourX) > 1e-12])

    wall = PrescribedWall([raoThroatArc(nozzle.throatRadiusNonDimensional,
                                        nozzle.throatOutletCurvatureNonDimensional,
                                        float(nozzle.throatEndAngle)),
                           SampledSegment(contourX[advancing], contourR[advancing])])

    startSlice = slice(int(nozzle.numCharacteristics) - 1, None)
    blocks = (nozzle.allMachNumbers[1], nozzle.allFlowAngles[1],
              nozzle.allXPoints[1], nozzle.allRPoints[1])
    startingLine = tuple(np.asarray(block, dtype = float)[startSlice, -1] for block in blocks)
    usable = np.isfinite(startingLine[0]) & (startingLine[0] > 1.0)

    return wall, tuple(array[usable] for array in startingLine), xWall

@pytest.fixture(scope = 'module')
def marchOverTheIdealWall(truncatedIdeal):
    '''The forward march run over the inverse solve's own converged wall.'''
    gas = CharacteristicGas(truncatedIdeal.chamberGamma, truncatedIdeal.chamberRGasConstant,
                            truncatedIdeal.chamberStagnationTemperature)
    wall, startingLine, xWall = wallAndStartingLine(truncatedIdeal)

    return marchPrescribedWall(gas, wall, startingLine), xWall

#--------------------------------------------------------------------------------------------------------------------------#
# -- The manufactured solution -- #
#--------------------------------------------------------------------------------------------------------------------------#

def testTheMarchReachesTheExitOnAnIdealWall(marchOverTheIdealWall):
    '''
    A truncated ideal wall carries no compression to coalesce, so the march has nothing to stop it
    short. Terminating on anything but the exit means it failed to solve a case it must solve.
    '''
    march, _ = marchOverTheIdealWall
    assert march['terminated'] == 'exit'

def testTheForwardMarchReproducesTheInverseSolveItShouldAgreeWith(marchOverTheIdealWall,
                                                                  truncatedIdeal):
    '''
    The check the module is settled by. Both solvers are answering the same question on the same
    wall in the same gas, so the near-wall Mach numbers have to agree to the discretization and
    nothing more. Measured at 0.0097 worst and 0.0022 rms when this was written.
    '''
    march, xWall = marchOverTheIdealWall
    marchedX = np.asarray(march['wallX'], dtype = float)
    marchedMach = np.asarray(march['wallMach'], dtype = float)

    # The contour solution's own diverging near-wall Mach. The attribute of the same name on the
    # nozzle is the full contour including the converging section, on a different abscissa.
    inverseWallMach = np.asarray(truncatedIdeal.nozzleContourSolution.nozzleNearWallMachNumber,
                                 dtype = float)
    inside = marchedX <= xWall.max()
    difference = marchedMach[inside] - np.interp(marchedX[inside], xWall, inverseWallMach)

    assert inside.sum() > 20
    assert np.abs(difference).max() < 0.02
    assert np.sqrt(np.mean(difference**2)) < 0.005

def testTheInteriorCarriesNothingFasterThanTheExit(marchOverTheIdealWall, truncatedIdeal):
    '''
    A truncated ideal contour is designed to straighten its exit, so the exit plane is close to
    uniform and no node inside it should be running meaningfully faster than the design Mach
    number. This does not hold for the optimized families, whose exit planes are non-uniform by
    construction, which is why it is asserted here and not of them.
    '''
    march, _ = marchOverTheIdealWall
    mesh = np.asarray(march['mach'], dtype = float)
    finite = np.isfinite(mesh)

    assert finite.sum() > 1000
    assert mesh[finite].max() < truncatedIdeal.exitMachNumber * 1.02

def testACleanWallFoldsNowhere(marchOverTheIdealWall):
    '''
    A fold is two characteristics of the same family crossing, which a truncated ideal contour
    cannot produce: its wall is a streamline of a shock-free field. Counting zero of them here is
    what makes a non-zero count on another wall meaningful rather than noise.
    '''
    march, _ = marchOverTheIdealWall
    assert march['foldedLines'] == 0

def testAFoldedStepIsRejectedRatherThanKept(marchOverTheIdealWall):
    '''
    The guard the fold count reports on. Marching along a line runs downstream and inward, so a
    point that lands upstream and further out has folded back on itself. Such a point returns
    finite, supersonic and at positive radius, so none of the other guards see it, and before this
    one existed a thrust-optimized contour kept one at Mach 7.53 and minus forty degrees.

    Asserted as a property of what survives: every step along every solved line advances.
    '''
    march, _ = marchOverTheIdealWall
    x = np.asarray(march['x'], dtype = float)
    r = np.asarray(march['r'], dtype = float)

    for line in range(x.shape[1]):
        finite = np.isfinite(x[:, line]) & np.isfinite(r[:, line])
        if finite.sum() < 3:
            continue
        axial, radial = x[finite, line], r[finite, line]
        regressed = (np.diff(axial) <= 0.0) & (np.diff(radial) >= 0.0)
        assert not regressed.any(), f'line {line} kept a step that folded back on itself'
