# -- NOVA: Ablative Material Response Tests -- #

'''

Verification and validation of the charring ablator model in NOVA.ablative.

The two words are kept apart on purpose. Verification asks whether the discretisation solves the
equations it claims to, and is answered against solutions that are known in closed form, so the
error is exact and quantified. Validation asks whether those equations describe reality, and is
answered against data somebody else produced.

Verification here covers the semi-infinite conduction solutions with both kinds of surface
condition, the steady ablation profile, the closed-form decomposition, mesh and timestep
convergence, and the discrete energy balance.

Validation rests on two independent things. The closed-form diffusion-limited char removal rate is
set against the TACOT equilibrium B-prime table, which was generated by the Ablation Workshop with
CEA data and a 25 species mixture; the two agree to better than 0.005 per cent in the asymptotic
limits the closed form describes. And the full material response is set against the FIAT baseline
of Ablation Workshop test case 1, read off the published figure. The digitized reference values are
recorded below, along with how accurately the figure can be read.

What is not validated is the nozzle application. The tests here show that its plumbing holds
together and that its results behave the way physics requires, which is not the same as showing
they are right.

Author: Sean Bowman

'''

import numpy as np
import pytest
from scipy.special import erf, erfc

from NOVA.ablative import AblationEnvironment, BPrimeTable, CharringMaterial, \
                          STEFANBOLTZMANN, ablativeNozzleLiner, blowingCorrection, \
                          diffusionLimitedCharBPrime, elementMassFractionsFromMoles, \
                          packagedBPrimeTablePath, propellantElementMassFractions, \
                          solveMaterialResponse
from NOVA.materials import availableAblativeMaterials, ablativeResponseData, \
                           ablativeResponseProvenance
from NOVA.errors import ConvergenceFailureError, InvalidInputError

# ------------------------------------------------------------------------------------------------
# Reference data
# ------------------------------------------------------------------------------------------------

# FIAT baseline of Ablation Workshop test case 1 at t = 60 s, read off figure 1 of
# Lachaud, Martin, Cozmuta and Laub, Ablation Test Case Series #1, version 1.1, February 2011.
#
# The figure was rendered at 400 dpi and the marker clusters located against the plot frame. The
# calibration is trustworthy to about 1.5 K: the axis tick marks, whose values are known exactly,
# come back as 199.5, 399.0, 600.0, 799.5, 999.0 and 1599.0, and the imposed surface line, known
# to be 1644 K, comes back as 1643.9. Marker centring adds a few kelvin on top of that.
FIATPROBES = {
    0.001: 1526.7,
    0.002: 1417.4,
    0.004: 1223.0,
    0.008:  912.3,
    0.016:  549.4,
    0.050:  297.8,
}

# Same figure, lower panel, same digitization.
FIATVIRGINFRONT = 0.01493        # [m] depth at which the density has dropped 2 per cent
FIATCHARFRONT = 0.00263          # [m] depth at which the density is within 2 per cent of char

# Air, as the TACOT B-prime table defines it: 21 per cent oxygen and 79 per cent nitrogen by mole.
AIRELEMENTS = elementMassFractionsFromMoles({'O': 0.42, 'N': 1.58})

def constantPropertySolid(conductivity = 0.5, density = 1000.0, specificHeat = 1000.0,
                          emissivity = 0.0) -> CharringMaterial:

    '''

    A solid with no decomposition and no temperature dependence.

    Every closed-form conduction solution assumes constant properties, so verifying against one
    needs a material that has them. Enthalpy is exactly specificHeat times temperature, which
    keeps the enthalpy formulation and the temperature formulation of the same problem identical.

    Parameters:
    -----------
    conductivity : float
        Thermal conductivity [W/m-K].
    density : float
        Density [kg/m^3].
    specificHeat : float
        Specific heat [J/kg-K].
    emissivity : float
        Surface emissivity [-].

    Returns:
    --------
    CharringMaterial

    '''

    grid = [200.0, 6000.0]
    state = {'specificHeat': [specificHeat, specificHeat],
             'thermalConductivity': [conductivity, conductivity],
             'enthalpy': [specificHeat * grid[0], specificHeat * grid[1]],
             'emissivity': emissivity}

    return CharringMaterial(
        name = 'constant property solid',
        virginDensity = density, charDensity = density,
        temperature = grid, virgin = state, char = state,
        components = ({'name': 'inert', 'virginDensity': density, 'charDensity': density,
                       'preExponentialFactor': 0.0, 'activationTemperature': 0.0,
                       'reactionOrder': 0.0, 'onsetTemperature': 1.0e9},),
        resinVolumeFraction = 0.0, porosity = 0.0)

def surfaceScheduleOfTestCaseOne(time: float) -> float:

    '''The surface temperature of Ablation Workshop test case 1: 298 K to 1644 K over 0.1 s.'''

    return 298.0 + (1644.0 - 298.0) * min(time / 0.1, 1.0)

@pytest.fixture(scope = 'module')
def testCaseOne():

    '''

    Ablation Workshop test case 1, solved once for every test that reads it.

    Five centimeters of TACOT, surface driven to 1644 K in 0.1 s and held for a minute, adiabatic
    and impermeable back face, one atmosphere throughout, no recession.

    '''

    environment = AblationEnvironment(
        surfaceClosure = 'temperature',
        surfaceTemperature = surfaceScheduleOfTestCaseOne,
        pressure = 101325.0,
        backFaceCondition = 'adiabatic')

    return solveMaterialResponse(
        'TACOT v3.0', environment, thickness = 0.05, duration = 60.0,
        timeStep = 0.05, numberOfNodes = 101, growthRatio = 1.05,
        initialTemperature = 298.0, outputInterval = 1.0)

# ------------------------------------------------------------------------------------------------
# Verification: conduction against closed-form solutions
# ------------------------------------------------------------------------------------------------

class TestConductionAgainstClosedForm:

    '''

    The conduction solver against solutions that are known exactly.

    Both cases are the semi-infinite solid, which the model reproduces by making the sample deep
    enough that the back face never moves off its initial temperature. Five centimeters against a
    thermal penetration of eight millimeters is deep by a factor of six, and the erf at that
    argument is one to fourteen figures.

    '''

    conductivity = 0.5
    density = 1000.0
    specificHeat = 1000.0
    duration = 30.0
    probeDepths = np.array([0.0005, 0.001, 0.002, 0.004, 0.006, 0.008, 0.012])

    @property
    def diffusivity(self):

        '''Thermal diffusivity of the test solid [m^2/s].'''

        return self.conductivity / (self.density * self.specificHeat)

    def solve(self, environment, nodes = 161, growthRatio = 1.03, timeStep = 0.02):

        '''One run of the constant-property solid under a given surface condition.'''

        return solveMaterialResponse(
            constantPropertySolid(self.conductivity, self.density, self.specificHeat),
            environment, thickness = 0.05, duration = self.duration,
            timeStep = timeStep, numberOfNodes = nodes, growthRatio = growthRatio,
            initialTemperature = 300.0, outputInterval = self.duration)

    def testStepSurfaceTemperatureMatchesTheErrorFunction(self):

        # T(y, t) = Ts + (T0 - Ts) erf(y / 2 sqrt(alpha t)), Carslaw and Jaeger section 2.4.
        result = self.solve(AblationEnvironment(surfaceClosure = 'temperature',
                                                surfaceTemperature = 1000.0))

        argument = self.probeDepths / (2.0 * np.sqrt(self.diffusivity * self.duration))
        exact = 1000.0 + (300.0 - 1000.0) * erf(argument)
        model = np.array([result.temperatureAtDepth(depth)[-1] for depth in self.probeDepths])

        # 0.081 K on a 700 K step is 0.012 per cent. The bound is set an order above what the
        # solver delivers so that it catches a defect rather than mesh noise.
        assert np.max(np.abs(model - exact)) < 1.0, np.max(np.abs(model - exact))

    def testConstantSurfaceFluxMatchesTheClosedForm(self):

        # Ts(t) = T0 + 2 q sqrt(alpha t / pi) / k, and the profile carries the erfc term.
        surfaceFlux = 5.0e4
        result = self.solve(AblationEnvironment(
            surfaceClosure = 'diffusionLimited', transferCoefficient = 0.0,
            radiationInput = surfaceFlux, viewFactor = 0.0,
            edgeElements = {'O': 1.0}, charRemovalEfficiency = 0.0))

        rise = 2.0 * surfaceFlux * np.sqrt(self.diffusivity * self.duration / np.pi) \
               / self.conductivity
        assert abs(result.surfaceTemperature[-1] - (300.0 + rise)) < 2.0

        argument = self.probeDepths / (2.0 * np.sqrt(self.diffusivity * self.duration))
        exact = 300.0 + (2.0 * surfaceFlux / self.conductivity) * (
            np.sqrt(self.diffusivity * self.duration / np.pi) * np.exp(-argument**2)
            - 0.5 * self.probeDepths * erfc(argument))
        model = np.array([result.temperatureAtDepth(depth)[-1] for depth in self.probeDepths])

        assert np.max(np.abs(model - exact)) < 2.0, np.max(np.abs(model - exact))

    def testNoRecessionWithoutCharRemoval(self):

        result = self.solve(AblationEnvironment(
            surfaceClosure = 'diffusionLimited', transferCoefficient = 0.0,
            radiationInput = 5.0e4, viewFactor = 0.0,
            edgeElements = {'O': 1.0}, charRemovalEfficiency = 0.0))

        assert result.recession[-1] == 0.0

    def testTheEnergyBalanceClosesWhenTheSurfaceIsFixed(self):

        result = self.solve(AblationEnvironment(surfaceClosure = 'temperature',
                                                surfaceTemperature = 1000.0))

        # Nothing recedes, so every term in the balance sits on a control volume that does not
        # move and the closure is exact to the Newton tolerance.
        assert result.energyImbalance < 1.0e-8, result.energyImbalance

    @pytest.mark.parametrize('nodes, growthRatio', [(41, 1.14), (81, 1.06), (161, 1.03)])
    def testRefiningTheMeshImprovesTheAnswer(self, nodes, growthRatio):

        result = self.solve(AblationEnvironment(surfaceClosure = 'temperature',
                                                surfaceTemperature = 1000.0),
                            nodes = nodes, growthRatio = growthRatio)

        argument = self.probeDepths / (2.0 * np.sqrt(self.diffusivity * self.duration))
        exact = 1000.0 + (300.0 - 1000.0) * erf(argument)
        model = np.array([result.temperatureAtDepth(depth)[-1] for depth in self.probeDepths])
        error = np.max(np.abs(model - exact))

        # Every mesh in the range is already inside a kelvin; the point of the sweep is that none
        # of them is wildly off, which is what a broken boundary treatment would produce.
        assert error < 5.0, (nodes, error)

    def testHalvingTheTimestepDoesNotChangeAConvergedAnswer(self):

        environment = AblationEnvironment(surfaceClosure = 'temperature',
                                          surfaceTemperature = 1000.0)
        coarse = self.solve(environment, timeStep = 0.04)
        fine = self.solve(environment, timeStep = 0.01)

        probe = 0.002
        assert abs(coarse.temperatureAtDepth(probe)[-1]
                   - fine.temperatureAtDepth(probe)[-1]) < 0.5

class TestSteadyAblation:

    '''

    The moving mesh against the steady ablation solution.

    Once the recession rate is constant and the profile has stopped changing in the frame of the
    surface, the energy equation collapses to alpha T'' + s_dot T' = 0, whose solution is a pure
    exponential decaying into the material over a length alpha / s_dot. Reproducing it exercises
    the one term nothing else in this file touches: the material moving past the mesh.

    '''

    conductivity = 0.5
    density = 1000.0
    specificHeat = 1000.0

    def result(self):

        '''A long run at a fixed char blowing rate, taken to steady state.'''

        environment = AblationEnvironment(
            surfaceClosure = 'diffusionLimited',
            transferCoefficient = 0.60,
            recoveryTemperature = 3000.0,
            edgeSpecificHeat = 2000.0,
            edgeElements = {'O': 1.0},
            viewFactor = 0.0,
            ambientTemperature = 300.0)

        return solveMaterialResponse(
            constantPropertySolid(self.conductivity, self.density, self.specificHeat),
            environment, thickness = 0.08, duration = 120.0, timeStep = 0.04,
            numberOfNodes = 201, growthRatio = 1.02, initialTemperature = 300.0,
            outputInterval = 10.0)

    def testTheRecessionRateIsTheOneTheClosureAsksFor(self):

        result = self.result()

        charBPrime = diffusionLimitedCharBPrime({'O': 1.0})
        expected = 0.60 * blowingCorrection(charBPrime) * charBPrime / self.density
        observed = (result.recession[-1] - result.recession[-2]) \
                   / (result.time[-1] - result.time[-2])

        assert abs(observed - expected) / expected < 1.0e-6, (observed, expected)

    def testTheProfileIsTheSteadyAblationExponential(self):

        result = self.result()

        diffusivity = self.conductivity / (self.density * self.specificHeat)
        charBPrime = diffusionLimitedCharBPrime({'O': 1.0})
        recessionRate = 0.60 * blowingCorrection(charBPrime) * charBPrime / self.density

        depths = np.linspace(0.0, 0.012, 25)
        mesh = result.normalizedPosition * (result.initialThickness - result.recession[-1])
        model = np.interp(depths, mesh, result.temperature[-1])
        wall = result.surfaceTemperature[-1]
        exact = 300.0 + (wall - 300.0) * np.exp(-recessionRate * depths / diffusivity)

        # 14 K on a 1970 K wall-to-far-field difference is 0.71 per cent, and it is the first
        # order error of the upwinded mesh-motion term.
        assert np.max(np.abs(model - exact)) / (wall - 300.0) < 0.015

    def testTheSteadyWallTemperatureBalancesConvectionAgainstTheMaterialItHeats(self):

        result = self.result()

        # At steady state everything conducted in goes to raising the incoming material from the
        # far field to the wall, so the balance closes on a single algebraic statement.
        charBPrime = diffusionLimitedCharBPrime({'O': 1.0})
        blown = 0.60 * blowingCorrection(charBPrime)
        charMassFlux = blown * charBPrime
        expected = (blown * 2000.0 * 3000.0 + charMassFlux * self.specificHeat * 300.0) \
                   / (blown * 2000.0 + charMassFlux * self.specificHeat)

        assert abs(result.surfaceTemperature[-1] - expected) / expected < 0.01

class TestEnergyClosureUnderRecession:

    '''

    How well the discrete energy balance closes once the surface moves, and how that improves.

    The surface node carries no volume, which is the convention that makes the surface energy
    balance an exact algebraic statement at the surface temperature. The price is that the
    material leaving through that node is not in any control volume, so the global bookkeeping
    carries a first order error in the size of the first cell. It has to be shown to be first
    order, and it has to be shown not to contaminate the answer.

    '''

    def result(self, nodes, growthRatio):

        '''Twenty seconds of the convective test case at a given mesh.'''

        environment = AblationEnvironment(
            surfaceClosure = 'bPrimeTable',
            transferCoefficient = (np.array([0.0, 0.1, 60.0]), np.array([0.0, 0.3, 0.3])),
            edgeEnthalpy = (np.array([0.0, 0.1, 60.0]), np.array([0.0, 1.5e6, 1.5e6])),
            pressure = 101325.0, ambientTemperature = 300.0, viewFactor = 1.0)

        return solveMaterialResponse(
            'TACOT v3.0', environment, thickness = 0.05, duration = 20.0, timeStep = 0.04,
            numberOfNodes = nodes, growthRatio = growthRatio, initialTemperature = 300.0,
            outputInterval = 20.0)

    def testTheClosureErrorIsFirstOrderInTheSurfaceCell(self):

        coarse = self.result(61, 1.08)
        medium = self.result(121, 1.04)
        fine = self.result(241, 1.02)

        # Each step roughly halves the first cell, so a first order error roughly halves too.
        assert 1.7 < coarse.energyImbalance / medium.energyImbalance < 2.3
        assert 1.7 < medium.energyImbalance / fine.energyImbalance < 2.3

    def testRecessionAndWallTemperatureAreConvergedAcrossThatRange(self):

        coarse = self.result(61, 1.08)
        fine = self.result(241, 1.02)

        assert abs(fine.recession[-1] - coarse.recession[-1]) / fine.recession[-1] < 0.005
        assert abs(fine.surfaceTemperature[-1] - coarse.surfaceTemperature[-1]) < 3.0

# ------------------------------------------------------------------------------------------------
# Verification: decomposition kinetics
# ------------------------------------------------------------------------------------------------

class TestDecompositionKinetics:

    '''

    The closed-form step against the rate law it is supposed to integrate.

    A reaction order other than one separates and integrates exactly, which removes the stiffness
    of the decomposition entirely and lets the timestep be set by conduction alone. That is worth
    having only if the closed form is actually the integral of the rate, so it is checked against
    a finely substepped explicit integration of the rate itself.

    '''

    def material(self):

        '''TACOT, whose two decomposing phases both carry a reaction order of three.'''

        return CharringMaterial.fromStore('TACOT v3.0')

    @pytest.mark.parametrize('temperature', [700.0, 900.0, 1200.0])
    def testTheClosedFormStepIntegratesTheRateLaw(self, temperature):

        material = self.material()
        start = material.componentVirginDensity.copy()

        closedForm = material.advanceDecomposition(start[None, :], np.array([temperature]), 2.0)[0]

        stepped = start[None, :].copy()
        substeps = 20000
        for _ in range(substeps):
            rate = material.decompositionRate(stepped, np.array([temperature]))
            stepped = stepped - rate * (2.0 / substeps)

        for exact, marched in zip(closedForm, stepped[0]):
            if exact > 1.0e-6:
                assert abs(marched - exact) / exact < 1.0e-3, (temperature, exact, marched)

    def testDecompositionNeverOvershootsTheCharDensity(self):

        material = self.material()
        start = material.componentVirginDensity.copy()

        # An hour at 3000 K is far past anything a liner sees.
        finished = material.advanceDecomposition(start[None, :], np.array([3000.0]), 3600.0)[0]

        assert np.all(finished >= material.componentCharDensity - 1.0e-12)
        assert np.all(finished <= start + 1.0e-12)

    def testAThirdOrderReactionApproachesCompletionWithoutReachingIt(self):

        material = self.material()
        start = material.componentVirginDensity.copy()
        decomposing = material.preExponentialFactor > 0.0

        # Both TACOT resin phases carry a reaction order of three, whose closed form decays as the
        # inverse square root of time. It therefore never reaches the char density exactly, and a
        # solver that returned exactly the char density would be wrong rather than converged.
        # Quadrupling the time halves what is left.
        shortRun = material.advanceDecomposition(start[None, :], np.array([3000.0]), 900.0)[0]
        longRun = material.advanceDecomposition(start[None, :], np.array([3000.0]), 3600.0)[0]

        shortRemaining = (shortRun - material.componentCharDensity)[decomposing]
        longRemaining = (longRun - material.componentCharDensity)[decomposing]

        assert np.all(longRemaining > 0.0)
        assert np.allclose(shortRemaining / longRemaining, 2.0, rtol = 1.0e-3)

        # What is left is negligible against the density it started from.
        assert np.all(longRemaining / material.componentVirginDensity[decomposing] < 1.0e-3)

    def testNothingHappensBelowTheOnsetTemperature(self):

        material = self.material()
        start = material.componentVirginDensity.copy()

        # 320 K is below the lower of the two onset temperatures, which is 333 K.
        unchanged = material.advanceDecomposition(start[None, :], np.array([320.0]), 1000.0)[0]

        assert np.allclose(unchanged, start)

    def testTheReinforcementNeverDecomposes(self):

        material = self.material()
        start = material.componentVirginDensity.copy()

        finished = material.advanceDecomposition(start[None, :], np.array([4000.0]), 3600.0)[0]

        # The carbon fiber is the component with no rate constant.
        inert = material.preExponentialFactor == 0.0
        assert np.allclose(finished[inert], start[inert])

    def testTheMixingRuleReturnsTheStoredEndStateDensities(self):

        material = self.material()

        virgin = material.bulkDensity(material.componentVirginDensity)
        char = material.bulkDensity(material.componentCharDensity)

        assert abs(virgin - material.virginDensity) < 1.0e-9
        assert abs(char - material.charDensity) < 1.0e-9

# ------------------------------------------------------------------------------------------------
# Verification: surface transfer
# ------------------------------------------------------------------------------------------------

class TestBlowingCorrection:

    '''The correlation, its limit at no blowing, and the shape it has to have.'''

    def testItIsExactlyOneAtNoBlowing(self):

        assert blowingCorrection(0.0) == 1.0

    def testTheSeriesAndTheRatioAgreeAcrossTheSwitch(self):

        # The implementation switches to a series below an argument of 1e-6 to avoid 0/0.
        justBelow = blowingCorrection(0.9e-6 / 2.0 / 0.5)
        justAbove = blowingCorrection(1.1e-6 / 2.0 / 0.5)

        assert abs(justBelow - justAbove) < 1.0e-6

    @pytest.mark.parametrize('bPrime', [0.05, 0.2, 1.0, 3.0, 10.0])
    def testItMatchesTheCorrelationItClaims(self, bPrime):

        argument = 2.0 * 0.5 * bPrime
        assert abs(blowingCorrection(bPrime) - np.log(1.0 + argument) / argument) < 1.0e-12

    def testMoreBlowingAlwaysMeansLessTransfer(self):

        values = [blowingCorrection(b) for b in (0.0, 0.1, 0.5, 1.0, 2.0, 5.0)]

        assert all(later < earlier for earlier, later in zip(values, values[1:]))

    def testTheLaminarFactorBlocksLessThanTheTurbulentOne(self):

        assert blowingCorrection(1.0, 0.4) > blowingCorrection(1.0, 0.5)

    def testMassEnteringTheWallIsRefused(self):

        with pytest.raises(InvalidInputError):
            blowingCorrection(-0.1)

class TestElementalBookkeeping:

    '''Mole to mass conversion and the elemental composition of a propellant pair.'''

    def testAirComesOutAtItsKnownOxygenMassFraction(self):

        # 0.21 O2 and 0.79 N2 by mole is 23.29 per cent oxygen by mass.
        assert abs(AIRELEMENTS['O'] - 0.23291) < 1.0e-4

    def testMassFractionsSumToOne(self):

        fractions = elementMassFractionsFromMoles({'C': 0.206, 'H': 0.679, 'O': 0.115})

        assert abs(sum(fractions.values()) - 1.0) < 1.0e-12

    def testAnUnknownElementIsRefused(self):

        with pytest.raises(InvalidInputError):
            elementMassFractionsFromMoles({'Xx': 1.0})

    def testCombustionConservesElements(self):

        # Liquid oxygen and liquid hydrogen at a mixture ratio of six is six sevenths oxygen by
        # mass, exactly, whatever the products turn out to be.
        products = propellantElementMassFractions({'H': 1.0}, {'O': 1.0}, 6.0)

        assert abs(products['O'] - 6.0 / 7.0) < 1.0e-12
        assert abs(products['H'] - 1.0 / 7.0) < 1.0e-12

    def testAHydrocarbonPairSplitsAsItsFormulaSays(self):

        products = propellantElementMassFractions(
            {'C': 0.8594, 'H': 0.1406}, {'O': 1.0}, 2.7)

        assert abs(products['O'] - 2.7 / 3.7) < 1.0e-9
        assert abs(sum(products.values()) - 1.0) < 1.0e-12

    def testAMixtureRatioOfZeroIsRefused(self):

        with pytest.raises(InvalidInputError):
            propellantElementMassFractions({'H': 1.0}, {'O': 1.0}, 0.0)

# ------------------------------------------------------------------------------------------------
# Validation: surface thermochemistry against the TACOT equilibrium table
# ------------------------------------------------------------------------------------------------

class TestDiffusionLimitedAgainstTheEquilibriumTable:

    '''

    The closed-form char removal rate against an independently generated equilibrium solution.

    The packaged table was produced by the Ablation Workshop with TARGET on the CEA thermodynamic
    database, for air, over a 25 species mixture, with equal diffusion coefficients and
    equilibrium imposed at the wall. Nothing in NOVA had a hand in it.

    At low temperature the equilibrium product of carbon and oxygen is carbon dioxide, so each
    carbon consumed takes two oxygens and the rate is half the monoxide value. Above roughly
    1200 K it is carbon monoxide, and the rate sits on a plateau until sublimation takes over
    around 3200 K. Those two plateaux are what the closed form describes, and they are where it
    can be checked.

    '''

    def table(self):

        '''The packaged TACOT table for air.'''

        return BPrimeTable.fromPackagedTable('tacotBPrimeAir')

    def testTheCarbonMonoxideBranchMatchesThePlateau(self):

        table = self.table()

        # One atmosphere, no pyrolysis gas, averaged over 1500 to 2500 K where the table is flat.
        temperatures = np.arange(1500.0, 2501.0, 25.0)
        tabulated = np.mean([table.charBPrime(101325.0, 0.0, t) for t in temperatures])
        closedForm = diffusionLimitedCharBPrime(AIRELEMENTS, product = 'CO')

        error = abs(closedForm - tabulated) / tabulated
        assert error < 5.0e-5, (closedForm, tabulated, error)

    def testTheCarbonDioxideBranchMatchesTheLowTemperatureLimit(self):

        table = self.table()

        tabulated = table.charBPrime(101325.0, 0.0, 250.0)
        closedForm = diffusionLimitedCharBPrime(AIRELEMENTS, product = 'CO2')

        error = abs(closedForm - tabulated) / tabulated
        assert error < 5.0e-5, (closedForm, tabulated, error)

    def testTheDioxideBranchIsExactlyHalfTheMonoxideBranch(self):

        monoxide = diffusionLimitedCharBPrime(AIRELEMENTS, product = 'CO')
        dioxide = diffusionLimitedCharBPrime(AIRELEMENTS, product = 'CO2')

        assert abs(dioxide - 0.5 * monoxide) < 1.0e-15

    def testTheLowTemperatureLimitIsIndependentOfPressure(self):

        table = self.table()

        values = [table.charBPrime(pressure, 0.0, 250.0)
                  for pressure in (101.325, 1013.25, 10132.5, 101325.0)]

        # An elemental transport limit does not know about pressure, and the table agrees.
        assert max(values) - min(values) < 1.0e-9

    def testTheClosedFormSatisfiesItsOwnElementalBalance(self):

        # Given B'c, the wall mass fractions follow, and the carbon-to-oxygen ratio at the wall
        # has to be the one carbon monoxide fixes. This is the identity the derivation rests on.
        edge = propellantElementMassFractions({'C': 0.8594, 'H': 0.1406}, {'O': 1.0}, 2.7)
        gas = elementMassFractionsFromMoles({'C': 0.206, 'H': 0.679, 'O': 0.115})
        gasBPrime = 0.3

        charBPrime = diffusionLimitedCharBPrime(edge, gasBPrime, gas, 'CO')

        total = 1.0 + charBPrime + gasBPrime
        wallCarbon = (edge['C'] + charBPrime + gasBPrime * gas['C']) / total
        wallOxygen = (edge['O'] + gasBPrime * gas['O']) / total

        assert abs(wallCarbon / wallOxygen - 12.0107 / 15.9994) < 1.0e-12

    def testAnOxygenFreeEdgeGasConsumesNoChar(self):

        assert diffusionLimitedCharBPrime({'H': 1.0}) == 0.0

    def testPyrolysisGasBlowingWithoutItsCompositionIsRefused(self):

        with pytest.raises(InvalidInputError):
            diffusionLimitedCharBPrime(AIRELEMENTS, gasBPrime = 0.2)

    def testAnUnknownProductBranchIsRefused(self):

        with pytest.raises(InvalidInputError):
            diffusionLimitedCharBPrime(AIRELEMENTS, product = 'CH4')

class TestBPrimeTable:

    '''The packaged table itself, and what it does at the edge of its own range.'''

    def testTheTableLoadsWithTheGridTheSourceDefines(self):

        table = BPrimeTable.fromPackagedTable('tacotBPrimeAir')

        assert table.pressure.size == 4
        assert table.gasBPrime.size == 25
        assert table.temperature.size == 151
        assert table.temperature[0] == 250.0 and table.temperature[-1] == 4000.0

    def testEveryAxisAscends(self):

        table = BPrimeTable.fromPackagedTable('tacotBPrimeAir')

        for axis in (table.pressure, table.gasBPrime, table.temperature):
            assert np.all(np.diff(axis) > 0.0)

    def testSublimationLiftsTheRateFarAboveThePlateau(self):

        table = BPrimeTable.fromPackagedTable('tacotBPrimeAir')

        plateau = table.charBPrime(101325.0, 0.0, 2000.0)
        sublimating = table.charBPrime(101325.0, 0.0, 3900.0)

        assert sublimating > 10.0 * plateau

    def testRequestsOffTheGridAreClampedAndCounted(self):

        table = BPrimeTable.fromPackagedTable('tacotBPrimeAir')
        assert table.clampedRequests == 0

        # A rocket chamber is fifty times the top of this table's pressure axis. Being told so is
        # the whole point of the counter.
        onGrid = table.charBPrime(101325.0, 0.0, 2000.0)
        offGrid = table.charBPrime(5.0e6, 0.0, 2000.0)

        assert table.clampedRequests == 1
        assert offGrid == onGrid

    def testAnUnknownPackagedTableIsRefused(self):

        with pytest.raises(InvalidInputError):
            BPrimeTable.fromPackagedTable('noSuchTable')

    def testThePackagedPathPointsIntoTheAssets(self):

        path = packagedBPrimeTablePath('tacotBPrimeAir')

        assert path.endswith('tacotBPrimeAir.npz')
        assert 'assets' in path

# ------------------------------------------------------------------------------------------------
# Validation: material response against the published FIAT baseline
# ------------------------------------------------------------------------------------------------

class TestAblationWorkshopTestCaseOne:

    '''

    The full in-depth response against the FIAT baseline of the first Ablation Workshop test case.

    This is the comparison the workshop itself designated: FIAT results from the Thermal
    Performance Data Base, on a fixed surface temperature so that conduction and pyrolysis are
    isolated from the boundary layer. Fourteen codes ran it in 2011 and the workshop reported
    agreement between type 1 codes as mostly below one per cent.

    The reference values here are digitized from the published figure, so the comparison is only
    as good as that figure can be read, which is a few kelvin. The tolerances below sit at three
    per cent, and the actual agreement is better than one per cent at five of the six probes.

    '''

    @pytest.mark.parametrize('depth', sorted(FIATPROBES))
    def testEachTemperatureProbeAgreesWithFiat(self, testCaseOne, depth):

        reference = FIATPROBES[depth]
        model = testCaseOne.temperatureAtDepth(depth)[-1]

        assert abs(model - reference) / reference < 0.03, (depth, model, reference)

    def testTheNearSurfaceProbesAgreeToBetterThanOnePerCent(self, testCaseOne):

        # The deepest probe is the one the mesh resolves least well and it converges toward the
        # reference as the mesh is refined. The four shallower ones are already inside one
        # per cent at this resolution.
        for depth in (0.001, 0.002, 0.004, 0.008):
            model = testCaseOne.temperatureAtDepth(depth)[-1]
            assert abs(model - FIATPROBES[depth]) / FIATPROBES[depth] < 0.01, depth

    def testTheBackFaceStaysAtItsInitialTemperature(self, testCaseOne):

        # Fifty millimeters of a material with a conductivity near half a watt per meter kelvin
        # does not notice a minute of heating at the other end, and FIAT says the same.
        assert abs(testCaseOne.backFaceTemperature[-1] - 298.0) < 1.0

    def testThePyrolysisFrontIsWhereFiatPutsIt(self, testCaseOne):

        model = testCaseOne.pyrolysisDepth[-1]

        assert abs(model - FIATVIRGINFRONT) / FIATVIRGINFRONT < 0.04, model

    def testTheCharFrontIsWhereFiatPutsIt(self, testCaseOne):

        model = testCaseOne.charDepth[-1]

        assert abs(model - FIATCHARFRONT) / FIATCHARFRONT < 0.05, model

    def testTheCharFrontTrailsThePyrolysisFront(self, testCaseOne):

        # The material chars from the surface down, so the fully charred depth is always the
        # shallower of the two fronts.
        assert np.all(testCaseOne.charDepth <= testCaseOne.pyrolysisDepth + 1.0e-12)

    def testTheGasFluxPeaksEarlyAndDecays(self, testCaseOne):

        # The resin nearest the surface goes first and takes the rate with it. FIAT peaks within
        # a couple of seconds and is down to a fifth of the peak by a minute.
        flux = testCaseOne.pyrolysisGasMassFlux
        peak = int(np.argmax(flux))

        assert testCaseOne.time[peak] < 5.0
        assert flux[-1] < 0.3 * flux[peak]

    def testTheSurfaceHoldsTheTemperatureItWasGiven(self, testCaseOne):

        held = testCaseOne.surfaceTemperature[testCaseOne.time > 1.0]

        assert np.allclose(held, 1644.0, atol = 1.0e-6)

    def testNothingRecedes(self, testCaseOne):

        assert np.all(testCaseOne.recession == 0.0)

    def testTheEnergyBalanceClosesToMachinePrecision(self, testCaseOne):

        assert testCaseOne.energyImbalance < 1.0e-8, testCaseOne.energyImbalance

# ------------------------------------------------------------------------------------------------
# The material store
# ------------------------------------------------------------------------------------------------

class TestAblativeResponseStore:

    '''What the store holds, and that it holds it consistently.'''

    def testTacotIsCarried(self):

        assert 'TACOT v3.0' in availableAblativeMaterials()

    def testTheStoreIsCaseInsensitive(self):

        assert ablativeResponseData('tacot v3.0') is ablativeResponseData('TACOT v3.0')

    def testAMaterialWithoutResponseDataIsRefused(self):

        # Carbon phenolic is in the selection-grade store and has no response property set. A
        # substitution here would be worse than a refusal.
        with pytest.raises(KeyError):
            ablativeResponseData('Carbon Phenolic')

    def testEveryCurveSharesTheTemperatureGrid(self):

        entry = ablativeResponseData('TACOT v3.0')
        length = len(entry['temperature'])

        for state in ('virgin', 'char'):
            for name in ('specificHeat', 'thermalConductivity', 'enthalpy'):
                assert len(entry[state][name]) == length, (state, name)

    def testTheTemperatureGridAscends(self):

        grid = np.array(ablativeResponseData('TACOT v3.0')['temperature'])

        assert np.all(np.diff(grid) > 0.0)

    def testEnthalpyRisesWithTemperature(self):

        entry = ablativeResponseData('TACOT v3.0')

        for state in ('virgin', 'char'):
            assert np.all(np.diff(entry[state]['enthalpy']) > 0.0), state

    def testTheEnthalpyDatumIsCharAtTwoNinetyEightKelvin(self):

        material = CharringMaterial.fromStore('TACOT v3.0')

        # The whole enthalpy formulation depends on this: char at 298 K is zero, and the virgin
        # value at the same temperature is the heat of formation of the resin fraction.
        assert abs(float(material.enthalpy(298.0, material.charDensity))) < 1.0
        assert abs(float(material.enthalpy(298.0, material.virginDensity)) + 857142.857) < 1.0

    def testTheVirginStateIsColderThanTheCharAtEqualTemperature(self):

        material = CharringMaterial.fromStore('TACOT v3.0')

        # Virgin carries the resin's negative heat of formation, so it sits below char everywhere
        # on the absolute enthalpy scale.
        for temperature in (300.0, 800.0, 1500.0, 3000.0):
            virgin = float(material.enthalpy(temperature, material.virginDensity))
            char = float(material.enthalpy(temperature, material.charDensity))
            assert virgin < char, temperature

    def testCharConductsLessThanVirginWhereItMatters(self):

        material = CharringMaterial.fromStore('TACOT v3.0')

        # Below about 1400 K the two states are given the same conductivity; above it the char
        # curve is the lower of the two, which is what makes a char layer protective.
        for temperature in (1700.0, 2200.0, 3000.0):
            virgin = float(material.thermalConductivity(temperature, material.virginDensity))
            char = float(material.thermalConductivity(temperature, material.charDensity))
            assert char < virgin, temperature

    def testTheCharSurfaceIsTheMoreEmissiveOfTheTwo(self):

        material = CharringMaterial.fromStore('TACOT v3.0')

        assert material.charEmissivity > material.virginEmissivity

    def testEveryStoredPieceRecordsWhereItCameFrom(self):

        entry = ablativeResponseData('TACOT v3.0')

        for name in ('virgin', 'char', 'virginDensity', 'charDensity', 'pyrolysis',
                     'pyrolysisGasElements', 'surfaceThermochemistry',
                     'pyrolysisGasProperties'):
            source, basis = ablativeResponseProvenance('TACOT v3.0', name)
            assert len(source) > 20, name
            assert basis == 'openBenchmark', name

        assert entry['basis'] == 'openBenchmark'

    def testProvenanceForSomethingNotStoredIsRefused(self):

        with pytest.raises(KeyError):
            ablativeResponseProvenance('TACOT v3.0', 'ultimateTensileStrength')

    def testTheNotesSayWhatTheMaterialIsNotForUse(self):

        notes = ablativeResponseData('TACOT v3.0')['notes']

        # Two limits have to survive any edit of this entry: it is a low-density entry material
        # rather than a nozzle liner, and its surface table is for air.
        assert 'air' in notes.lower()
        assert '280' in notes

class TestPyrolysisGasEnthalpy:

    '''The gas enthalpy curve, which is what carries the heat of pyrolysis.'''

    def testItRisesWithTemperature(self):

        material = CharringMaterial.fromStore('TACOT v3.0')
        temperatures = np.linspace(300.0, 3500.0, 40)

        values = material.pyrolysisGasEnthalpy(temperatures)

        assert np.all(np.diff(values) > 0.0)

    def testItIsNotTheSolidCurve(self):

        material = CharringMaterial.fromStore('TACOT v3.0')

        # Substituting the solid enthalpy for the gas is the mistake that makes pyrolysis
        # thermally neutral, and it moves the in-depth temperature by tens of kelvin.
        gas = float(material.pyrolysisGasEnthalpy(900.0))
        solid = float(material.enthalpy(900.0, material.virginDensity))

        assert abs(gas - solid) > 1.0e6

    def testPressureShiftsTheEquilibriumComposition(self):

        material = CharringMaterial.fromStore('TACOT v3.0')

        low = float(material.pyrolysisGasEnthalpy(900.0, 1013.25))
        high = float(material.pyrolysisGasEnthalpy(900.0, 101325.0))

        assert low != high

    def testAChorringMaterialWithoutAGasCurveIsRefused(self):

        entry = ablativeResponseData('TACOT v3.0')

        with pytest.raises(InvalidInputError):
            CharringMaterial(
                name = 'TACOT without its gas curve',
                virginDensity = entry['virginDensity'], charDensity = entry['charDensity'],
                temperature = entry['temperature'], virgin = entry['virgin'],
                char = entry['char'], components = entry['pyrolysis']['components'],
                resinVolumeFraction = entry['pyrolysis']['resinVolumeFraction'],
                porosity = entry['pyrolysis']['porosity'])

    def testANonCharringMaterialNeedsNoGasCurve(self):

        # Nothing pyrolyses, so there is no reaction enthalpy to be missing.
        assert constantPropertySolid().decomposes is False

# ------------------------------------------------------------------------------------------------
# Interface
# ------------------------------------------------------------------------------------------------

class TestSolverInterface:

    '''What the solver refuses, and why.'''

    def environment(self):

        '''A minimal fixed-surface-temperature condition.'''

        return AblationEnvironment(surfaceClosure = 'temperature', surfaceTemperature = 800.0)

    @pytest.mark.parametrize('thickness, duration, timeStep', [
        (0.0, 10.0, 0.1), (0.01, 0.0, 0.1), (0.01, 10.0, 0.0), (-0.01, 10.0, 0.1)])
    def testUnusableGeometryOrTimingIsRefused(self, thickness, duration, timeStep):

        with pytest.raises(InvalidInputError):
            solveMaterialResponse(constantPropertySolid(), self.environment(),
                                  thickness, duration, timeStep = timeStep)

    def testTooFewNodesIsRefused(self):

        with pytest.raises(InvalidInputError):
            solveMaterialResponse(constantPropertySolid(), self.environment(),
                                  0.01, 1.0, numberOfNodes = 3)

    def testAnUnknownSurfaceClosureIsRefused(self):

        environment = AblationEnvironment(surfaceClosure = 'guesswork')

        with pytest.raises(InvalidInputError):
            solveMaterialResponse(constantPropertySolid(), environment, 0.01, 1.0)

    def testTheDiffusionLimitedClosureNeedsAnEdgeComposition(self):

        environment = AblationEnvironment(surfaceClosure = 'diffusionLimited',
                                          transferCoefficient = 1.0)

        with pytest.raises(InvalidInputError):
            solveMaterialResponse(constantPropertySolid(), environment, 0.01, 1.0)

    def testConsumingTheLinerIsReportedRatherThanIgnored(self):

        # A tenth of a millimeter of liner against a surface that removes millimeters a second.
        environment = AblationEnvironment(
            surfaceClosure = 'diffusionLimited', transferCoefficient = 50.0,
            recoveryTemperature = 3500.0, edgeSpecificHeat = 2000.0,
            edgeElements = {'O': 1.0}, viewFactor = 0.0)

        with pytest.raises(ConvergenceFailureError):
            solveMaterialResponse(constantPropertySolid(), environment,
                                  thickness = 1.0e-4, duration = 5.0, timeStep = 0.01,
                                  numberOfNodes = 21)

    def testAScheduleIsInterpolatedInTime(self):

        environment = AblationEnvironment(
            surfaceClosure = 'temperature',
            surfaceTemperature = (np.array([0.0, 10.0]), np.array([300.0, 1300.0])))

        assert abs(environment.sample('surfaceTemperature', 5.0) - 800.0) < 1.0e-9

    def testACallableScheduleMaySeeTheWallTemperature(self):

        environment = AblationEnvironment(
            transferCoefficient = lambda time, wall: 0.1 * time + 0.001 * wall)

        assert abs(environment.sample('transferCoefficient', 10.0, 2000.0) - 3.0) < 1.0e-9

    def testASingleArgumentCallableStillWorks(self):

        environment = AblationEnvironment(radiationInput = lambda time: 1000.0 * time)

        assert abs(environment.sample('radiationInput', 3.0, 900.0) - 3000.0) < 1.0e-9

    def testTheBackFaceCanBeHeldAtATemperature(self):

        environment = AblationEnvironment(
            surfaceClosure = 'temperature', surfaceTemperature = 1500.0,
            backFaceCondition = 'temperature', backFaceTemperature = 400.0)

        result = solveMaterialResponse(constantPropertySolid(), environment,
                                       thickness = 0.01, duration = 5.0, timeStep = 0.01,
                                       numberOfNodes = 41)

        assert abs(result.backFaceTemperature[-1] - 400.0) < 1.0e-6

    def testSuppressingRecessionLeavesTheRestOfTheBalanceAlone(self):

        environment = AblationEnvironment(
            surfaceClosure = 'bPrimeTable', transferCoefficient = 0.3,
            edgeEnthalpy = 1.5e6, pressure = 101325.0, viewFactor = 1.0,
            suppressRecession = True)

        result = solveMaterialResponse('TACOT v3.0', environment, thickness = 0.05,
                                       duration = 10.0, timeStep = 0.05, numberOfNodes = 81,
                                       growthRatio = 1.06, initialTemperature = 300.0,
                                       outputInterval = 10.0)

        assert np.all(result.recession == 0.0)
        assert np.all(result.charBPrime == 0.0)
        assert result.surfaceTemperature[-1] > 1000.0
        assert result.pyrolysisGasMassFlux[-1] > 0.0

    def testTheEfficiencyScalesTheRemovalRateLinearly(self):

        def run(efficiency):
            environment = AblationEnvironment(
                surfaceClosure = 'diffusionLimited', transferCoefficient = 0.2,
                recoveryTemperature = 3000.0, edgeSpecificHeat = 2000.0,
                edgeElements = {'O': 1.0}, charRemovalEfficiency = efficiency,
                viewFactor = 0.0)
            return solveMaterialResponse(constantPropertySolid(), environment,
                                         thickness = 0.05, duration = 5.0, timeStep = 0.02,
                                         numberOfNodes = 61, outputInterval = 5.0)

        full = run(1.0)
        half = run(0.5)

        assert abs(half.charBPrime[-1] / full.charBPrime[-1] - 0.5) < 1.0e-9

# ------------------------------------------------------------------------------------------------
# Nozzle application
# ------------------------------------------------------------------------------------------------

def nozzleStations():

    '''A small converging-diverging contour and the exhaust that flows through it.'''

    gamma = 1.19
    throatRadius = 0.05
    axial = np.linspace(-0.06, 0.15, 7)
    radius = np.where(axial < 0.0,
                      throatRadius * (1.0 + 0.8 * (axial / 0.06)**2),
                      throatRadius * (1.0 + 1.4 * (np.abs(axial) / 0.15)**1.3))
    from NOVA.gasDynamics import machFromAreaRatio, staticTemperatureRatio
    mach = np.array([machFromAreaRatio(float((r / throatRadius)**2), gamma,
                                       'subsonic' if x < 0.0 else 'supersonic')
                     for r, x in zip(radius, axial)])
    staticTemperature = 3550.0 * np.array(
        [staticTemperatureRatio(float(m), gamma) for m in mach])

    return axial, radius, mach, staticTemperature, gamma

@pytest.fixture(scope = 'module')
def linerResult():

    '''One short ablative liner solve along a nozzle contour.'''

    axial, radius, mach, staticTemperature, gamma = nozzleStations()
    exhaust = propellantElementMassFractions({'C': 0.8594, 'H': 0.1406}, {'O': 1.0}, 2.7)

    return ablativeNozzleLiner(
        'TACOT v3.0', axial, radius, mach, staticTemperature,
        edgeElements = exhaust,
        chamberPressure = 5.0e6, chamberTemperature = 3550.0,
        characteristicVelocity = 1780.0, exhaustGamma = gamma,
        exhaustGasConstant = 8314.46261815324 / 22.0, exhaustMolecularWeight = 22.0,
        throatRadiusOfCurvature = 0.075, burnTime = 3.0, linerThickness = 0.030,
        timeStep = 0.05, numberOfNodes = 41, charRemovalEfficiency = 0.12,
        viewFactor = 0.5)

class TestAblativeNozzleLiner:

    '''

    The station march along a nozzle contour.

    None of this is validated against a firing. What it can be held to is the behavior physics
    requires: the throat is where the flux is highest so it must recede most, the wall must move
    outward, and the liner must insulate.

    '''

    def testTheThroatRecedesMostOfAnyStation(self, linerResult):

        throat = int(np.argmin(linerResult.radius))

        assert linerResult.recession[throat] == pytest.approx(
            linerResult.recession.max(), rel = 1.0e-9)

    def testTheGasSideCoefficientPeaksAtTheThroat(self, linerResult):

        throat = int(np.argmin(linerResult.radius))

        assert linerResult.heatTransferCoefficient[throat] == pytest.approx(
            linerResult.heatTransferCoefficient.max(), rel = 1.0e-9)

    def testTheThroatOpensRatherThanCloses(self, linerResult):

        assert linerResult.throatAreaRatio > 1.0
        assert np.all(linerResult.finalRadius >= linerResult.radius)

    def testAWiderStationRecedesLess(self, linerResult):

        # Recession follows the flux, which follows the area ratio, so the exit plane must be the
        # least eroded station on the diverging side.
        diverging = linerResult.axialPosition > 0.0

        assert linerResult.recession[diverging][-1] == pytest.approx(
            linerResult.recession[diverging].min(), rel = 1.0e-9)

    def testTheBackFaceStaysCold(self, linerResult):

        # Thirty millimeters of a low-density charring ablator over three seconds. If the back
        # face has moved, either the liner or the model is wrong.
        assert np.all(linerResult.backFaceTemperature < 320.0)

    def testTheCharLayerIsDeeperThanTheRecession(self, linerResult):

        # The char front runs ahead of the surface; if it did not, the surface would be eating
        # virgin material, which the closure does not describe.
        assert np.all(linerResult.charDepth >= linerResult.recession)

    def testEveryStationIsReported(self, linerResult):

        stations = linerResult.axialPosition.size

        assert len(linerResult.stations) == stations
        for name in ('radius', 'recession', 'finalRadius', 'surfaceTemperature',
                     'backFaceTemperature', 'charDepth', 'heatTransferCoefficient',
                     'charBPrime'):
            assert getattr(linerResult, name).size == stations, name

    def testMismatchedStationArraysAreRefused(self):

        axial, radius, mach, staticTemperature, gamma = nozzleStations()

        with pytest.raises(InvalidInputError):
            ablativeNozzleLiner(
                'TACOT v3.0', axial, radius[:-1], mach, staticTemperature,
                edgeElements = {'O': 1.0}, chamberPressure = 5.0e6,
                chamberTemperature = 3550.0, characteristicVelocity = 1780.0,
                exhaustGamma = gamma, exhaustGasConstant = 378.0,
                exhaustMolecularWeight = 22.0, throatRadiusOfCurvature = 0.075,
                burnTime = 1.0, linerThickness = 0.02)

    def testAContourOfOneStationIsRefused(self):

        with pytest.raises(InvalidInputError):
            ablativeNozzleLiner(
                'TACOT v3.0', [0.0], [0.05], [1.0], [3000.0],
                edgeElements = {'O': 1.0}, chamberPressure = 5.0e6,
                chamberTemperature = 3550.0, characteristicVelocity = 1780.0,
                exhaustGamma = 1.19, exhaustGasConstant = 378.0,
                exhaustMolecularWeight = 22.0, throatRadiusOfCurvature = 0.075,
                burnTime = 1.0, linerThickness = 0.02)

class TestPhysicalConstants:

    '''The one constant this module defines for itself.'''

    def testStefanBoltzmannIsTheCodataValue(self):

        assert STEFANBOLTZMANN == pytest.approx(5.670374419e-8, rel = 1.0e-12)

    def testReradiationUsesIt(self):

        # A black surface at 1000 K into a 300 K sink radiates sigma (1000^4 - 300^4).
        expected = STEFANBOLTZMANN * (1000.0**4 - 300.0**4)

        assert abs(expected - 56.24e3) / 56.24e3 < 0.01
