
# -- The Forward Characteristics Problem -- #

'''

Marching a characteristics net against a wall that was given rather than solved for.

A truncated ideal contour solves the inverse problem. Its downstream boundary is prescribed, a
uniform axial exit line, and the wall falls out of the mesh as the streamline that reaches it. The
wall is an output.

A thrust-optimized parabola and a thrust-optimized contour invert that. Their wall is drawn first,
from two angles in one case and by an optimizer in the other, and the flow has to be solved on it.
That is the forward problem, and it is a different march: the boundary that is known has swapped
ends, so the direction the net is built in swaps with it. The truncated ideal march steps inward
from a known exit line toward an unknown wall; this one steps outward from a known wall toward the
axis.

The unit processes are the same ones. `characteristics.axisymmetricMethodOfCharacteristics` for an
interior point, `characteristics.axisPoint` on the centerline, and
`contourKernel.wallIntersection` where a characteristic reaches the wall. Nothing here
reimplements a compatibility relation, which is what keeps the two families' interiors
comparable: a difference between a truncated ideal contour and a parabola solved here is a
difference between the walls, not between two approximations of the same equations.

The mesh
--------

Right-running characteristics are launched from the wall and marched to the axis, one per line.
Index `i` runs along a line, zero at the wall and increasing toward the axis; index `j` selects
the line and increases downstream. A point `[i, j]` is where line `j` crosses the left-running
characteristic arriving from `[i + 1, j - 1]`, one step closer to the axis on the line before it.

Line length is preserved as the march advances: the wall contributes a point at the top, the axis
contributes one at the bottom, and the interior gives up one. So the net is a parallelogram in
index space rather than the triangle the throat kernel builds.

Unlike the throat kernel this needs no predictor and no corrector. The kernel integrates its
left-running family backwards from the wall and has to guess a wall point before it can solve for
one; here every step runs forward along both families from data that is already known.

Where it stops
--------------

Two ways. The wall runs out, which is the ordinary end of a nozzle, and the line budget runs out,
which is a guard rather than a result.

A crossing is not one of them. Two adjacent right-running lines meeting is compression coalescing
into an internal shock, which a truncated ideal contour cannot do by construction and both
thrust-optimized families can, so the march looks for it. But it records it and carries on rather
than stopping, and the flag is an indicator rather than a measurement.

What the flag is worth, stated plainly. It reliably separates the families it is meant to: a
truncated ideal contour's own wall reports nothing, and every thrust-optimized parabola tried
reports something, which is what the literature says of the two. What is NOT established is where
it says the shock is, or how it behaves on a badly over-turned wall, where it has been seen to
report nothing while flagging a gentler wall that ought to compress less. Until that is understood
the location should be read as "somewhere around here" and the absence of a flag should not be
read as the absence of a shock.

Detecting a crossing is also not capturing it. The net is isentropic through the fold, which is
defensible only while the shock is weak. Nothing here applies a Rankine-Hugoniot jump or carries
an entropy rise downstream, so a contour with a strong internal shock is solved as though it had
none.

Lengths are non-dimensional against the throat radius. Angles are in radians.

Validation status
-----------------

The check that settles this module needs no external reference: marched over a truncated ideal
contour's own converged wall, it has to reproduce that contour's near-wall state and thrust
coefficient. A truncated ideal wall is a streamline of a shock-free field, so the forward march
over it is solving the same problem the inverse march already solved, and the inverse march is
verified in `docs/NozzleContourValidation.md`. It is a manufactured solution generated by a solver
that has already been checked.

Beyond that: mass flux through every line must equal the choked throat flow, which is internal but
exact, and the unit processes carry their own second-order verification in
`tests/testCharacteristics.py`.

Not validated: the flowfield point by point, for the same reason the truncated ideal contour's is
not, which is that no source publishes a tabulated axisymmetric solution for a rocket bell. And
anything downstream of a detected fold, where the isentropic assumption the net is built on has
stopped holding.

Author: Sean Bowman

'''

import numpy as np

from .characteristics import CharacteristicGas, axisPoint, axisymmetricMethodOfCharacteristics
from .contourKernel import wallIntersection

def marchPrescribedWall(gas: CharacteristicGas, wall, startingLine: tuple,
                        startingStation: float = None, maxLines: int = 400,
                        numIterations: int = 2, detectShocks: bool = True,
                        closeOnExit: bool = True) -> dict:

    '''

    Solve the characteristics net bounded by a prescribed wall and the axis.

    Parameters:
    -----------
    gas : CharacteristicGas
        The gas the net is solved in. The same one the kernel was solved in, or the two solutions
        do not join.
    wall : PrescribedWall
        The wall, from `wallGeometry`. Its first segment is the throat arc the starting line came
        off, so stations on it are comparable with `startingStation`.
    startingLine : tuple
        (mach, flowAngle, x, r) arrays on the right-running characteristic bounding the throat
        kernel, ordered from the wall end to the axis. `contour.solveKernel` returns exactly this
        as the last column of its expansion kernel.
    startingStation : float
        Station on the wall the starting line begins at. None takes the end of the first segment,
        which is where the throat arc hands over to the contoured wall.
    maxLines : int
        Guard on the number of lines. Reaching it is a failure to converge on the exit, not a
        result.
    numIterations : int
        Passed to `wallIntersection`. Two restores the second-order accuracy the interior points
        already have.
    detectShocks : bool
        True looks for two adjacent lines crossing and records the first one found. It does not
        stop the march: the criterion is provisional, and halting on it would refuse solves that
        go on to reach the exit cleanly.
    closeOnExit : bool
        True adds a final line aimed at the exit lip when the ordinary march falls short of it,
        so the delivered area ratio is the requested one rather than whatever the last
        characteristic happened to reach.

    Returns:
    --------
    dict
        'mach', 'flowAngle', 'x', 'r' as (numLinePoints, numLines) blocks; the wall arrays;
        'terminated' saying why the march stopped; and the shock record when one was found.

    '''

    machLine, flowAngleLine, xLine, rLine = (np.asarray(array, dtype = float)
                                             for array in startingLine)
    numLinePoints = len(machLine)
    if numLinePoints < 3:
        raise ValueError('A starting line needs at least three points: a wall end, an interior '
                         'and an axis.')

    if startingStation is None:
        startingStation = 1.0

    machColumns      = [machLine]
    flowAngleColumns = [flowAngleLine]
    xColumns         = [xLine]
    rColumns         = [rLine]
    wallStations     = [startingStation]

    terminated, shock = 'lineBudget', None
    crossings = []
    innerReach = [numLinePoints - 1]

    for lineIndex in range(1, maxLines + 1):

        previousMach      = machColumns[-1]
        previousFlowAngle = flowAngleColumns[-1]
        previousX         = xColumns[-1]
        previousR         = rColumns[-1]

        mach      = np.full(numLinePoints, np.nan)
        flowAngle = np.full(numLinePoints, np.nan)
        x         = np.full(numLinePoints, np.nan)
        r         = np.full(numLinePoints, np.nan)

        # -- The wall point, from the left-running characteristic one step inboard behind it -- #
        landing = wallIntersection(gas, wall, previousMach[1], previousFlowAngle[1],
                                   previousX[1], previousR[1],
                                   minimumStation = wallStations[-1],
                                   numIterations = numIterations)
        if landing is False:
            terminated = 'wallEnd'
            break

        wallMach, wallAngle, wallX, wallR, wallStation = landing
        if not np.isfinite(wallMach) or wallMach <= 1.0:
            terminated = 'wallState'
            break

        mach[0], flowAngle[0], x[0], r[0] = wallMach, wallAngle, wallX, wallR

        # -- The interior, outward to inward, every step forward along both families -- #
        #
        # A point that fails ends this line rather than discarding it, and the march carries on
        # from what was solved. Both halves of that matter. The failures are at the inner end,
        # where the axisymmetric source term goes singular as the radius approaches zero, and
        # discarding the line over one bad point at the axis threw away every good point at the
        # wall: on a parabolic wall that stopped the march after a single line and left the
        # contour as the throat arc alone.
        #
        # What it costs is honest and bounded. The net loses its innermost point each line, so the
        # solved region narrows toward the axis as the march advances, and `innerReach` records
        # how much of each line survived so a reader can see it rather than infer it.
        lastValid, reachedAxis = 0, False
        for i in range(1, numLinePoints - 1):
            if not np.isfinite(previousMach[i + 1]) or not np.isfinite(previousX[i + 1]):
                break
            kernel = [previousMach[i + 1], previousFlowAngle[i + 1], previousX[i + 1], previousR[i + 1],
                      mach[i - 1],         flowAngle[i - 1],         x[i - 1],         r[i - 1]]
            mach[i], flowAngle[i], x[i], r[i] = axisymmetricMethodOfCharacteristics(gas, kernel)
            if not np.isfinite(mach[i]) or mach[i] <= 1.0:
                mach[i], flowAngle[i], x[i], r[i] = np.nan, np.nan, np.nan, np.nan
                break

            # A line ends at the axis, and where it ends is decided by the flow rather than by
            # how many points the line before it happened to have. A line that is shorter than
            # its predecessor runs out of interior before it runs out of index, and marching on
            # through takes the solve to a negative radius, which is the same nozzle reflected.
            # The points that come back from there are arithmetically finite and physically
            # meaningless, and they drag the exit plane and the axis ordering with them.
            if r[i] <= 0.0:
                mach[i], flowAngle[i], x[i], r[i] = np.nan, np.nan, np.nan, np.nan
                reachedAxis = True
                break

            lastValid = i

        if lastValid < 1:
            terminated = 'interiorState'
            break

        # -- The axis, where symmetry supplies the second relation -- #
        axisIndex = lastValid + 1 if reachedAxis else numLinePoints - 1
        if reachedAxis or lastValid == numLinePoints - 2:
            mach[axisIndex], flowAngle[axisIndex], x[axisIndex], r[axisIndex] = axisPoint(
                gas, mach[lastValid], flowAngle[lastValid], x[lastValid], r[lastValid])

        innerReach.append(lastValid)

        # -- Where the net folds -- #
        #
        # Every line is tested, not just the first that folds, because one crossing is a point and
        # what a shock needs is a locus. The march never stops on one: a fold means the isentropic
        # assumption has failed there, not that the solve has, and the wall downstream of it still
        # has to be marched so there is a nozzle to apply the loss to.
        if detectShocks:
            crossing = _firstCrossing(previousX, previousR, x, r,
                                      exitStation = wall.exitPoint[0])
            if crossing is not None:
                # The flow turning the two characteristics represent between them. This is the
                # deflection the coalesced front has to produce, and it is what sets the shock's
                # strength once it is put through the oblique shock relations.
                aheadAngle = float(np.interp(r[crossing], previousR[::-1], previousFlowAngle[::-1]))
                aheadMach  = float(np.interp(r[crossing], previousR[::-1], previousMach[::-1]))
                crossings.append({
                    'lineIndex':   lineIndex,
                    'pointIndex':  crossing,
                    'x':           float(x[crossing]),
                    'r':           float(r[crossing]),
                    'deflection':  float(abs(flowAngle[crossing] - aheadAngle)),
                    'machAhead':   aheadMach,
                    'machBehind':  float(mach[crossing]),
                })
                if shock is None:
                    shock = dict(crossings[-1])

        machColumns.append(mach)
        flowAngleColumns.append(flowAngle)
        xColumns.append(x)
        rColumns.append(r)
        wallStations.append(wallStation)

        if wallStation >= wall.endStation - 1e-9:
            terminated = 'exit'
            break

    # -- Close the last of the wall -- #
    #
    # The march places wall points where the characteristics happen to land, so the last one falls
    # short of the exit by whatever the local spacing is. On the worked case that is the final
    # two and a half per cent of the wall, which is a delivered area ratio of 39.3 against a
    # requested 40, and for a family whose selling point is delivering its design point exactly
    # that is not a rounding error, it is the claim.
    #
    # The fix is to aim the last line rather than let it land: find the point on the previous line
    # whose characteristic reaches the lip, by interpolating along that line, and march one more
    # line from there. The interpolation is along a characteristic the solve already produced
    # rather than across the field, so it adds no new physics.
    if terminated in ('wallEnd', 'wallState') and closeOnExit and len(machColumns) > 1:
        closing = _closeOnExit(gas, wall, machColumns[-1], flowAngleColumns[-1],
                               xColumns[-1], rColumns[-1], wallStations[-1], numIterations)
        if closing is not None:
            machColumns.append(closing[0])
            flowAngleColumns.append(closing[1])
            xColumns.append(closing[2])
            rColumns.append(closing[3])
            wallStations.append(wall.endStation)
            terminated = 'exit'

    stack = lambda columns: np.column_stack(columns)

    return {
        'mach':         stack(machColumns),
        'flowAngle':    stack(flowAngleColumns),
        'x':            stack(xColumns),
        'r':            stack(rColumns),
        'wallMach':     np.array([column[0] for column in machColumns]),
        'wallAngle':    np.array([column[0] for column in flowAngleColumns]),
        'wallX':        np.array([column[0] for column in xColumns]),
        'wallR':        np.array([column[0] for column in rColumns]),
        'wallStation':  np.array(wallStations),
        'numLines':     len(machColumns),
        'innerReach':   np.array(innerReach[:len(machColumns)]),
        'terminated':   terminated,
        'shock':        shock,
        'crossings':    crossings,
    }

def _closeOnExit(gas: CharacteristicGas, wall, previousMach: np.ndarray,
                 previousFlowAngle: np.ndarray, previousX: np.ndarray, previousR: np.ndarray,
                 previousStation: float, numIterations: int) -> tuple:

    '''

    One more line, aimed so that its wall point is the exit lip rather than wherever the
    characteristics happened to reach.

    The source of that line is not one of the previous line's points but a place between two of
    them. It is found by bisection on the fractional index: the wall station a characteristic
    reaches grows monotonically with how far along the line it starts, so the index whose
    characteristic lands on the lip is bracketed and squeezed.

    Interpolating along the line is interpolating along a characteristic the solve produced, which
    is where the state genuinely varies smoothly. It is not interpolation across the field.

    Returns the four arrays of the closing line, or None when the lip cannot be reached from this
    line at all, which is the honest answer when the mesh is too coarse to resolve the last of the
    wall.

    '''

    numLinePoints = len(previousMach)
    target = wall.endStation

    def landingStation(index: float) -> float:
        mach, flowAngle, x, r = (np.interp(index, np.arange(numLinePoints), array)
                                 for array in (previousMach, previousFlowAngle,
                                               previousX, previousR))
        landing = wallIntersection(gas, wall, mach, flowAngle, x, r,
                                   minimumStation = previousStation,
                                   numIterations = numIterations)
        return None if landing is False else landing[4]

    # The bracket sits between index zero and index one, and the reason is worth stating because
    # it is the opposite of the obvious guess. Index zero is the previous line's own wall point,
    # so a characteristic leaving it reaches the wall immediately, just past where that line
    # already is. Index one is the point the ordinary march just tried and missed with, which
    # means its characteristic lands beyond the lip. The source that lands on the lip is therefore
    # between them, not further down the line: moving toward the axis sends the landing further
    # downstream, not less far.
    lower, upper = 0.0, 1.0
    lowerStation = None

    for _ in range(60):
        middle = 0.5 * (lower + upper)
        station = landingStation(middle)
        if station is not None and station < target:
            lower, lowerStation = middle, station
        else:
            upper = middle
        if upper - lower < 1e-12:
            break

    if lowerStation is None:
        return None

    # The last source that still lands, which puts the wall point at the lip from below rather
    # than a hair past it, where the wall no longer exists and the ray would report a miss.
    sourceIndex = lower

    # Shift the whole line onto the interpolated origin, so the closing step uses the same stencil
    # every other step used rather than a special case.
    indices = np.clip(np.arange(numLinePoints, dtype = float) + (sourceIndex - 1.0),
                      0.0, numLinePoints - 1)
    base = np.arange(numLinePoints)
    shiftedMach      = np.interp(indices, base, previousMach)
    shiftedFlowAngle = np.interp(indices, base, previousFlowAngle)
    shiftedX         = np.interp(indices, base, previousX)
    shiftedR         = np.interp(indices, base, previousR)

    mach      = np.full(numLinePoints, np.nan)
    flowAngle = np.full(numLinePoints, np.nan)
    x         = np.full(numLinePoints, np.nan)
    r         = np.full(numLinePoints, np.nan)

    landing = wallIntersection(gas, wall, shiftedMach[1], shiftedFlowAngle[1],
                               shiftedX[1], shiftedR[1], minimumStation = previousStation,
                               numIterations = numIterations)
    if landing is False:
        return None

    mach[0], flowAngle[0], x[0], r[0] = landing[0], landing[1], landing[2], landing[3]

    # A failed point ends this line rather than discarding it. The closing line exists to carry
    # the exit plane at the wall, and its inner end runs far downstream of the exit: on the worked
    # case the point that fails sits at a radius of 0.06 and an axial station of 43, against an
    # exit at 15.9. That is outside the nozzle twice over, and the part of the exit plane near the
    # axis is covered by the lines that came before. Losing it costs nothing; refusing to close
    # the wall over it costs the last two and a half per cent of the contour.
    #
    # The failure itself is the axisymmetric source term going singular as the radius goes to
    # zero, which is a known property of the formulation rather than of this line.
    lastValid = 0
    for i in range(1, numLinePoints - 1):
        kernel = [shiftedMach[i + 1], shiftedFlowAngle[i + 1], shiftedX[i + 1], shiftedR[i + 1],
                  mach[i - 1],        flowAngle[i - 1],        x[i - 1],        r[i - 1]]
        mach[i], flowAngle[i], x[i], r[i] = axisymmetricMethodOfCharacteristics(gas, kernel)
        if not np.isfinite(mach[i]) or mach[i] <= 1.0:
            mach[i], flowAngle[i], x[i], r[i] = np.nan, np.nan, np.nan, np.nan
            break
        lastValid = i

    if lastValid < 1:
        return None

    if lastValid == numLinePoints - 2:
        last = numLinePoints - 1
        mach[last], flowAngle[last], x[last], r[last] = axisPoint(
            gas, mach[last - 1], flowAngle[last - 1], x[last - 1], r[last - 1])

    return mach, flowAngle, x, r

def _firstCrossing(previousX: np.ndarray, previousR: np.ndarray, x: np.ndarray,
                   r: np.ndarray, exitStation: float = np.inf,
                   tolerance: float = 1e-9) -> int:

    '''

    Where a line has crossed the one before it, or None.

    Two adjacent right-running characteristics that converge and meet are compression waves
    coalescing into a shock, and the net has folded where that happens. The two lines are curves,
    so the comparison has to be made between curves: at any given radius, the later line must lie
    downstream of the earlier one. Where it does not, they have crossed.

    Radius is the right abscissa because both lines run from the wall to the axis and are
    monotone in it, so one can be interpolated onto the other without either being reordered.

    Three tests were tried before this one and the two that failed are worth recording, because
    both looked reasonable and both fired on flows that were perfectly smooth. Comparing the
    radius of points sharing an index on successive lines flags the wall opening out, which is the
    entire purpose of a diverging nozzle. Comparing their axial coordinates instead, whether
    against the same index or against the left-running parent, is no better: points sharing an
    index on adjacent characteristics are not at comparable stations, and on a parabolic wall the
    discrepancy grows steadily along the line and trips any threshold long before anything has
    crossed. Neither test was comparing like with like, which is what matching on radius fixes.

    '''

    # Only inside the nozzle. A right-running characteristic leaving the wall travels a long way
    # downstream before it reaches the axis, so most of every line lies past the exit plane, where
    # nothing it does can affect the contour. Left unbounded the search reports crossings at four
    # and five times the nozzle length, which are real features of the extended net and of no
    # interest to a nozzle.
    usable = np.isfinite(x) & np.isfinite(r) & (r > 0.0) & (x <= exitStation)
    earlier = np.isfinite(previousX) & np.isfinite(previousR) & (previousR > 0.0)
    if np.count_nonzero(usable) < 2 or np.count_nonzero(earlier) < 2:
        return None

    # np.interp needs an increasing abscissa, and both lines run outward to inward.
    earlierRadius = previousR[earlier][::-1]
    earlierAxial  = previousX[earlier][::-1]

    radius, axial = r[usable], x[usable]
    # Only where the earlier line actually spans this radius; extrapolating past its ends would
    # compare a point against a line that is not there.
    inside = (radius >= earlierRadius[0]) & (radius <= earlierRadius[-1])
    if not np.any(inside):
        return None

    behind = axial[inside] < np.interp(radius[inside], earlierRadius, earlierAxial) - tolerance
    if not np.any(behind):
        return None

    return int(np.flatnonzero(usable)[np.flatnonzero(inside)[np.argmax(behind)]])

#--------------------------------------------------------------------------------------------------------------------------#
# -- Capturing the shock the crossings imply -- #
#--------------------------------------------------------------------------------------------------------------------------#

'''

Detecting a fold says the isentropic march has stopped being valid somewhere. Capturing it says
how much that costs.

What follows is a weak-shock treatment and not a shock-fitting solver. The front is located from
where the characteristics cross, the oblique shock relations give the stagnation pressure lost
across it, and every streamline that passes through carries that loss from there on. What is NOT
done is re-solving the field behind the shock as a rotational one: entropy then varies from
streamline to streamline, which puts a Crocco term in the compatibility relations and makes the
interior point a different unit process. The march stays isentropic within each region.

That is defensible while the shock is weak, and weak has a number attached to it. The entropy rise
across an oblique shock departs from zero only at third order in shock strength, so a front whose
stagnation ratio is above about 0.99 loses little by being treated this way. Below that the
neglected term stops being small and the result should be read as a lower bound on the loss.

The reason it is worth having at all is not accounting. An isentropic solver charges a wall
nothing for turning, so a search over wall shapes turns as hard as its bounds allow and reports a
gain that does not exist. The loss computed here is what makes an over-turned wall look as bad as
it is.

'''

def shockFromDeflection(gas: CharacteristicGas, mach: float, deflection: float,
                        maximumPressureRatio: float = 50.0) -> tuple:

    '''

    The oblique shock that turns a flow through a given angle.

    `plume.obliqueShockState` answers the opposite question, taking a pressure ratio and returning
    the deflection it produces, and it is the validated routine of the pair. So rather than write
    a second set of shock relations this inverts that one, squeezing the pressure ratio until the
    deflection comes out right.

    Parameters:
    -----------
    gas : CharacteristicGas
        For the ratio of specific heats.
    mach : float
        Mach number ahead of the shock [-].
    deflection : float
        Flow turning the shock has to produce [rad].
    maximumPressureRatio : float
        Upper bound on the search.

    Returns:
    --------
    tuple : (pressureRatio, downstreamMach, stagnationRatio). A deflection at or below zero
    returns no shock at all.

    '''

    from .plume import obliqueShockState

    if mach <= 1.0 or deflection <= 0.0:
        return 1.0, mach, 1.0

    lower, upper = 1.0 + 1e-9, maximumPressureRatio

    # The strongest attached shock this Mach number supports bounds the search from above.
    # obliqueShockState reports detachment by returning a zero deflection, so walk the bound down
    # until it stops doing that.
    for _ in range(200):
        if obliqueShockState(mach, gas.gamma, upper)[0] > 0.0:
            break
        upper = lower + 0.5 * (upper - lower)

    strongest = obliqueShockState(mach, gas.gamma, upper)[0]
    if strongest <= 0.0:
        return 1.0, mach, 1.0

    if strongest < deflection:
        # The flow cannot turn this far through an attached shock. Report the strongest one
        # available rather than letting the turning happen for free, and let the caller see the
        # stagnation ratio that goes with it.
        pressureRatio = upper
    else:
        for _ in range(80):
            middle = 0.5 * (lower + upper)
            if obliqueShockState(mach, gas.gamma, middle)[0] < deflection:
                lower = middle
            else:
                upper = middle
        pressureRatio = 0.5 * (lower + upper)

    _, downstreamMach, stagnationRatio = obliqueShockState(mach, gas.gamma, pressureRatio)
    return float(pressureRatio), float(downstreamMach), float(stagnationRatio)

def captureShock(gas: CharacteristicGas, march: dict) -> dict:

    '''

    Turn a march's crossings into a shock front and the stagnation pressure it costs.

    The crossings arrive one per line, each the innermost point at which that line overtook the
    one before it. Together they trace the front. Each carries the flow turning its two
    characteristics represent between them, and those turnings ACCUMULATE along the front: a shock
    that has absorbed ten characteristics has turned the flow through the sum of their ten
    deflections rather than through the last one. That accumulation is what makes an over-turned
    wall expensive and a gently turning one nearly free.

    Parameters:
    -----------
    gas : CharacteristicGas
        The gas the net was solved in.
    march : dict
        What `marchPrescribedWall` returned.

    Returns:
    --------
    dict
        The front as arrays, the cumulative deflection and stagnation ratio along it, and the
        summary numbers a solution reports. None when no crossing was found.

    '''

    crossings = march.get('crossings') or []
    if not crossings:
        return None

    order = np.argsort([point['x'] for point in crossings])
    frontX = np.array([crossings[index]['x'] for index in order])
    frontR = np.array([crossings[index]['r'] for index in order])
    machAhead = np.array([crossings[index]['machAhead'] for index in order])
    cumulativeDeflection = np.cumsum([crossings[index]['deflection'] for index in order])

    pressureRatio, downstreamMach, stagnationRatio = [], [], []
    for index in range(len(frontX)):
        ratio, behind, stagnation = shockFromDeflection(gas, machAhead[index],
                                                        cumulativeDeflection[index])
        pressureRatio.append(ratio)
        downstreamMach.append(behind)
        stagnationRatio.append(stagnation)

    stagnationRatio = np.array(stagnationRatio)

    return {
        'x':                      frontX,
        'r':                      frontR,
        'machAhead':              machAhead,
        'deflection':             cumulativeDeflection,
        'pressureRatio':          np.array(pressureRatio),
        'downstreamMach':         np.array(downstreamMach),
        'stagnationRatio':        stagnationRatio,
        'onsetX':                 float(frontX[0]),
        'peakDeflection':         float(cumulativeDeflection[-1]),
        'minimumStagnationRatio': float(np.min(stagnationRatio)),
        'isWeak':                 bool(np.min(stagnationRatio) > 0.99),
        'numCrossings':           int(len(frontX)),
    }

def stagnationPressureField(chamberPressure: float, shock: dict, radius, axial):

    '''

    Stagnation pressure at a set of points, given a shock front they may sit behind.

    A point downstream of the front carries the loss the front has accumulated by the radius that
    point sits at; a point ahead of it carries the chamber value. The partition is by axial
    station at matched radius, which is the same comparison the crossing test is built on, and it
    smears the front across one cell rather than tracing streamlines through it.

    Parameters:
    -----------
    chamberPressure : float
        Stagnation pressure ahead of the shock [Pa].
    shock : dict
        What `captureShock` returned. None gives the chamber value everywhere.
    radius, axial : np.ndarray
        The points to evaluate at, non-dimensional.

    Returns:
    --------
    np.ndarray : stagnation pressure at each point [Pa]

    '''

    radius, axial = np.asarray(radius, dtype = float), np.asarray(axial, dtype = float)
    field = np.full(radius.shape, float(chamberPressure), dtype = float)
    if shock is None or len(shock['x']) < 2:
        return field

    order = np.argsort(shock['r'])
    frontRadius = shock['r'][order]
    frontAxial = shock['x'][order]
    frontRatio = shock['stagnationRatio'][order]

    usable = np.isfinite(radius) & np.isfinite(axial)
    within = usable & (radius >= frontRadius[0]) & (radius <= frontRadius[-1])
    behind = np.zeros(radius.shape, dtype = bool)
    behind[within] = axial[within] > np.interp(radius[within], frontRadius, frontAxial)

    field[behind] = chamberPressure * np.interp(radius[behind], frontRadius, frontRatio)
    return field

def shockFromWallEnvelope(gas: CharacteristicGas, wallX, wallR, wallAngle, wallMach,
                          exitStation: float) -> dict:

    '''

    Where the characteristics leaving the wall run into each other, and how hard.

    This replaces three earlier attempts that all asked the same wrong question. Each of them
    compared the POSITIONS of mesh points on adjacent lines and called a crossing a shock. What
    that actually measures is where the march has drifted, which near the axis it always does, and
    the answer it gave was backwards: the deflection it reported fell as the wall turned harder,
    the onset moved downstream, and the two most over-turned walls in a sweep reported no shock at
    all. A forty-seven degree turn cannot compress less than an eighteen degree one.

    The right question is about DIRECTIONS, not positions, and it is asked at the wall rather than
    out in the mesh. Every wall point launches a right-running characteristic at `theta - mu`. In
    a diverging section past the inflection the wall angle is falling, so each characteristic
    leaves at a shallower angle than the one before it and the family converges. Where two
    neighbours meet is where their compression has coalesced, and the earliest such meeting inside
    the nozzle is the onset. This is the classical envelope construction and it needs nothing from
    the interior of the mesh at all.

    The strength follows from the same place. What a shock at a point has to turn is the total
    wall turning of every characteristic that has reached it, so the deflection accumulates along
    the wall rather than being read off one pair.

    Parameters:
    -----------
    gas : CharacteristicGas
        For the ratio of specific heats.
    wallX, wallR : array
        Wall points the march placed, from the inflection outward, non-dimensional.
    wallAngle : array
        Flow angle at each, which at the wall is the wall angle [rad].
    wallMach : array
        Mach number at each [-].
    exitStation : float
        Axial station of the exit. Characteristics meeting beyond it leave the nozzle before they
        coalesce and are no part of its flow.

    Returns:
    --------
    dict
        The envelope points, the cumulative deflection reaching each, and the summary numbers.
        None when the family never converges, which is what a shock-free contour looks like.

    '''

    wallX = np.asarray(wallX, dtype = float)
    wallR = np.asarray(wallR, dtype = float)
    wallAngle = np.asarray(wallAngle, dtype = float)
    wallMach = np.asarray(wallMach, dtype = float)

    usable = (np.isfinite(wallX) & np.isfinite(wallR) & np.isfinite(wallAngle)
              & np.isfinite(wallMach) & (wallMach > 1.0))
    wallX, wallR = wallX[usable], wallR[usable]
    wallAngle, wallMach = wallAngle[usable], wallMach[usable]
    if len(wallX) < 3:
        return None

    machAngle = np.arcsin(np.clip(1.0 / wallMach, -1.0, 1.0))
    direction = wallAngle - machAngle                       # right-running, toward the axis

    meetX, meetR, turning, machAhead = [], [], [], []

    for index in range(len(wallX) - 1):
        firstSlope = np.tan(direction[index])
        secondSlope = np.tan(direction[index + 1])
        # Convergence is the LATER ray being steeper downward, which is worth spelling out
        # because the opposite reads as natural and is wrong. Along a bell wall the flow angle
        # falls and the Mach angle falls with it, and theta minus mu falls faster than either:
        # on the worked parabola it runs from plus 1.8 degrees at the inflection to minus 6.9 at
        # the exit. So each characteristic leaves aimed further inboard than the one before it,
        # and the family closes on itself. Requiring the reverse finds nothing, on any wall.
        if abs(firstSlope - secondSlope) < 1e-14 or secondSlope >= firstSlope:
            continue

        firstIntercept = wallR[index] - firstSlope * wallX[index]
        secondIntercept = wallR[index + 1] - secondSlope * wallX[index + 1]
        crossX = (secondIntercept - firstIntercept) / (firstSlope - secondSlope)
        crossR = firstSlope * crossX + firstIntercept

        # Downstream of both launch points, inside the nozzle, and not through the axis.
        if crossX <= wallX[index + 1] or crossX > exitStation or crossR <= 0.0:
            continue

        meetX.append(float(crossX))
        meetR.append(float(crossR))
        turning.append(float(max(0.0, wallAngle[index] - wallAngle[index + 1])))
        machAhead.append(float(wallMach[index]))

    if not meetX:
        return None

    order = np.argsort(meetX)
    meetX = np.array(meetX)[order]
    meetR = np.array(meetR)[order]
    machAhead = np.array(machAhead)[order]
    cumulativeTurning = np.cumsum(np.array(turning)[order])

    pressureRatio, downstreamMach, stagnationRatio = [], [], []
    for index in range(len(meetX)):
        ratio, behind, stagnation = shockFromDeflection(gas, machAhead[index],
                                                        cumulativeTurning[index])
        pressureRatio.append(ratio)
        downstreamMach.append(behind)
        stagnationRatio.append(stagnation)
    stagnationRatio = np.array(stagnationRatio)

    return {
        'x':                      meetX,
        'r':                      meetR,
        'machAhead':              machAhead,
        'deflection':             cumulativeTurning,
        'pressureRatio':          np.array(pressureRatio),
        'downstreamMach':         np.array(downstreamMach),
        'stagnationRatio':        stagnationRatio,
        'onsetX':                 float(meetX[0]),
        'peakDeflection':         float(cumulativeTurning[-1]),
        'minimumStagnationRatio': float(np.min(stagnationRatio)),
        'isWeak':                 bool(np.min(stagnationRatio) > 0.99),
        'numCrossings':           int(len(meetX)),
    }
