
# -- Volute Class Definition -- #

'''

You heard the man, make da volute!

This class definition structures the generation of Volute geometry.

----------------------------------------------------------------------
                Geometry Generation Conventions
----------------------------------------------------------------------

> The coordinate axes are as follows:
    - X (i_hat) is the direction of the incoming / outgoing fluid from
      the largest volute cross section
    - Y (j_hat) is the direction orthogonal to X (i_hat) in the plane
      of the scroll of the volute
    - Z (k_hat) completes orthogonality, and is the direction orthogonal
      to the fluid flow of the volute

> To that end, when planar cross sections are drawn they are created in
the YZ plane. This geometry convention aligns with the conventions of
traditional CAD softwares such that importing volute geometry from this
generator will line up with expectations and conventions for typical
CAD softwares.

> Outer walls can also be generated by passing in either a wall
thickness, array of wall thickness, or hoop stress parameters. To size
walls by hoop stress, both the target hoop stress and pressure 
differential between the fluid volume and ambient must be passed in.
Hoop stress wall thickness calculations are done with respect to the 
hydraulic diameter by calling the utils hoop stress calculator.

> The numbers a cross section measures live in voluteSections.py: the area, perimeter and
hydraulic diameter of each family, the area law that distributes them around the wrap, and where
an anchor puts a section relative to the scroll radius. This module draws and sweeps them. The
split is there because a family described once cannot drift between the generators that draw it.

> All units are in Mass Base SI
    - Length      [m]
    - Area        [m^2]
    - Volume      [m^3]
    - Temperature [K]
    - Pressure    [Pa]
    - Stress      [Pa]
    - Mass Flow   [kg/s]

Author: Sean Bowman

'''

import numpy as np
from tqdm import tqdm

from .exports import py2cad
from .geometryTools import DCM, intersection, parallelOffset
from .voluteSections import (SCROLLTYPES, VOLUTEPRINTABILITY, VOLUTESECTIONS, anchorOffset,
                             characteristicLengthFromArea, checkFamily,
                             checkScrollType, resolveScrollAreas,
                             scrollAreaDistribution, sectionHydraulicDiameter,
                             tongueGapAngle)

def sweptSectionAreas(x, y, z):

    '''

    Area each drawn cross section encloses [m^2].

    Taken on the swept mesh by Newell's method, which needs no projection, so it measures the
    surface that was written rather than the profile it was drawn from. A closed profile of `N`
    chords inscribed in a circle encloses `(N/2 pi) sin(2 pi/N)` of it, which is 0.43 per cent
    short at the forty points a volute is drawn with by default and falls as the square of the
    count.

    Parameters:
    -----------
    x, y, z : np.ndarray
        Swept coordinates, (numCrossSections, crossSectionResolution).

    Returns:
    --------
    np.ndarray
        Enclosed area of each section [m^2].

    '''

    x, y, z = [np.asarray(value, dtype = float) for value in (x, y, z)]

    if x.ndim != 2 or x.shape[0] == 0:
        return np.array([])

    areas = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        points = np.column_stack([x[i], y[i], z[i]])
        cross = np.cross(points, np.roll(points, -1, axis = 0))
        areas[i] = 0.5*np.linalg.norm(np.sum(cross, axis = 0))

    return areas

def rollAboutAxis(rollAngle, source, destination) -> None:

    '''

    Roll each cross section about the scroll axis into place, writing into `destination`.

    A cross section is drawn in the YZ plane and belongs at its own angle around the scroll, so
    the sweep is one rotation about Z per section. `geometryTools.DCM` builds the same
    `Rx @ Ry @ Rz` product this replaced, and with no rotation about X or Y those two factors are
    exactly the identity.

    Parameters:
    -----------
    rollAngle : np.ndarray
        Wrap angle of each cross section [rad].
    source : tuple
        The three coordinate arrays to roll, each (numCrossSections, points).
    destination : tuple
        The three arrays the rolled coordinates are written into, same shapes.

    '''

    sourceX, sourceY, sourceZ = source
    destinationX, destinationY, destinationZ = destination

    for i in range(len(rollAngle)):

        destinationX[i,:], destinationY[i,:], destinationZ[i,:] = \
            DCM(eulerAngles = [0, 0, rollAngle[i]],
                valueMatrix = [sourceX[i,:], sourceY[i,:], sourceZ[i,:]],
                rotationOrder = 'xyz')

def dynamicEggShell(yInnerCS, zInnerCS,
                    wallThickness:float=None,
                    wallHoopStress:float=None, pressureDifferential:float=None, hydraulicDiameter:float=None,
                    bendRadius=None, minimumThickness:float=0.0):

    '''

    dynamicEggShell takes the inner cross sections of a volute and applies a variable wall thickness
    inner cross sections should be passed in BEFORE rolling (i.e. all CSs still in the YZ plane)
    includes automatic linear gap closure
    requires parallelOffset() and intersection() from utils

    (N = number of cross sections, M = number of points p. cross section)
    inputs:
        yInnerCS[NxM  = x coordinates of inner cross sections
        zInnerCS[NxM] = y coordinates of inner cross sections
        options:
            thickness[N or 1]  = desired wall thickness for each cross section 
            OR
            wallHoopStress[1]       = target hoop stress of the volute walls including FoS [Pa]
            pressureDifferential[1] = pressure difference between fluid volume and ambient [Pa]
            hydraulicDiameter[N]    = hydraulic diameter, [m]
            bendRadius[N or 1]      = distance from the axis of revolution to each section centre,
                                      which carries the toroidal crotch correction, [m]
            minimumThickness[1]     = floor the sized thickness is held at, [m]
    outputs: 
        yOuter[NxM]  = y coordinates of outer cross sections
        zOuter[NxM]  = z coordinates of outer cross sections
        y1Prime[N]   = y offset of each outer cross section
        z1Prime[N]   = z offset of each outer cross section

        *y1' and z1' are useful if aligning volutes by outer surface instead of inner.
            *best practice to use this feature: inner CSs should start and end at (0,0)

    mahalo no ka heluhelu 'ana :)
            
    '''

    N = np.shape(yInnerCS)[0] # numCrossSections
    M = np.shape(yInnerCS)[1] # crossSectionResolution

    ## Determine wall thickness
    # catch invalid inputs
    if wallThickness is not None and wallHoopStress is not None:
        raise Exception('Please specify EITHER wall thickness OR wall hoop stress and pressure differential and hydraulic diameter.')
    # generate wall thicknesses if not specified
    if wallHoopStress is not None:

        if pressureDifferential is None or hydraulicDiameter is None:
            raise Exception('If sizing shell by hoop stress, please specify pressure differential.')

        wallThickness = np.zeros((N))
        bend = np.full(N, np.nan) if bendRadius is None \
            else np.broadcast_to(np.asarray(bendRadius, dtype = float), (N,))
        for i in range(N):
            wallThickness[i] = hoopStressCalculator(hoopStress = wallHoopStress,
                                                    pressureDifferential = pressureDifferential,
                                                    diameter = hydraulicDiameter[i],
                                                    bendRadius = None if np.isnan(bend[i])
                                                    else bend[i])
        # A printed wall cannot be thinner than the process draws, whatever the stress allows.
        wallThickness = np.maximum(wallThickness, minimumThickness)
    # catch prespecified wall thickness
    if np.isscalar(wallThickness) or (np.ndim(wallThickness) == 0
                                     and wallThickness is not None):
        # constant wall thickness
        wallThickness = float(wallThickness)*np.ones((N))
    else:
        # dynamic wall thickness
        wallThickness = np.atleast_1d(np.asarray(wallThickness, dtype = float))
        if wallThickness.size == 1:
            wallThickness = np.full(N, float(wallThickness[0]))
        elif wallThickness.size != N:
            raise ValueError(f'A wall thickness array must carry one value per cross section, '
                             f'{N} of them, or a single value. It carried {wallThickness.size}.')

    # preallocate
    yShellCS, zShellCS = [np.zeros((N,M)) for _ in range(2)]
    y1Prime, z1Prime = [np.zeros((N)) for _ in range(2)]
    # loop
    for i in range(N):

        yShellCS[i,:], zShellCS[i,:] = parallelOffset(yInnerCS[i,:],zInnerCS[i,:],wallThickness[i])

        if [yShellCS[i,0],zShellCS[i,0]] != [yShellCS[i,-1],zShellCS[i,-1]]: # mind the gap

            D = .1 # generic length, trimmed later w/ interection()

            dydxBackward  = (zShellCS[i,1]  - zShellCS[i,0]) /(yShellCS[i,1]  - yShellCS[i,0] )
            thetaBackward = np.arctan(dydxBackward)
            dydxForward   = (zShellCS[i,-2] - zShellCS[i,-1])/(yShellCS[i,-2] - yShellCS[i,-1])
            thetaForward  = np.arctan(dydxForward)

            dxBackward = (D*np.cos(thetaBackward))
            dyBackward = (D*np.sin(thetaBackward))
            dxForward  = (D*np.cos(thetaForward))
            dyForward  = (D*np.sin(thetaForward))

            xBackward1 = yShellCS[i, 0] + dxBackward
            yBackward1 = zShellCS[i, 0] + dyBackward
            xBackward2 = yShellCS[i, 0] - dxBackward
            yBackward2 = zShellCS[i, 0] - dyBackward

            xForward1  = yShellCS[i,-1] + dxForward
            yForward1  = zShellCS[i,-1] + dyForward
            xForward2  = yShellCS[i,-1] - dxForward
            yForward2  = zShellCS[i,-1] - dyForward

            [xNewClosure,yNewClosure] = intersection([xBackward1,xBackward2],[yBackward1,yBackward2],
                                                     [xForward1 ,xForward2 ],[yForward1 ,yForward2 ])

            # # Dubug plot
            # plt.figure()
            # plt.plot   ( yInnerCS[i,:],   zInnerCS[i,:],                       'b')
            # plt.scatter([yInnerCS[i,0]], [zInnerCS[i,0]], 100,marker='*',color='b')
            # plt.scatter([yInnerCS[i,-1]],[zInnerCS[i,-1]],100,marker='*',color='c')
            # plt.plot   ( yShellCS[i,:],   zShellCS[i,:],                       'r')
            # plt.scatter([yShellCS[i,0]], [zShellCS[i,0]], 100,marker='*',color='r')
            # plt.scatter([yShellCS[i,-1]],[zShellCS[i,-1]],100,marker='*',color='m')
            # plt.plot   ([xBackward1,xBackward2],[yBackward1,yBackward2],       'y'   )
            # plt.plot   ([xForward1 ,xForward2 ],[yForward1 ,yForward2 ],       'lime')
            # plt.axis('equal')
            # plt.show(block = True)

            yShellCS[i, 0] = xNewClosure[0][0]
            zShellCS[i, 0] = yNewClosure[0][0]
            yShellCS[i,-1] = xNewClosure[0][0]
            zShellCS[i,-1] = yNewClosure[0][0]

        # # Dubug plot
        # plt.figure()
        # plt.plot   ( yInnerCS[i,:],   zInnerCS[i,:],                       'b')
        # plt.scatter([yInnerCS[i,0]], [zInnerCS[i,0]], 100,marker='*',color='b')
        # plt.scatter([yInnerCS[i,-1]],[zInnerCS[i,-1]],100,marker='*',color='c')
        # plt.plot   ( yShellCS[i,:],   zShellCS[i,:],                       'r')
        # plt.scatter([yShellCS[i,0]], [zShellCS[i,0]], 100,marker='*',color='r')
        # plt.scatter([yShellCS[i,-1]],[zShellCS[i,-1]],100,marker='*',color='m')
        # plt.axis('equal')
        # plt.show(block = True)

        y1Prime[i] = yShellCS[i,0]
        z1Prime[i] = zShellCS[i,0]

    return yShellCS, zShellCS, y1Prime, z1Prime, wallThickness

def toroidalCrotchFactor(diameter, bendRadius):

    '''

    How much more membrane stress a torus carries at its inner crotch than a straight tube [-].

    For a toroidal shell of tube radius `a` on a bend radius `R` under internal pressure `p`, the
    membrane stress around the tube is

        sigma = (p a)/(2 t) (2R + a sin(phi))/(R + a sin(phi))

    which tends to the straight cylinder value `p a / t` as `R` grows. It peaks where the tube
    faces the axis, `sin(phi) = -1`, and the factor returned is that peak over the straight tube
    value: `(2R - a)/(2(R - a))`.

    Parameters:
    -----------
    diameter : float or np.ndarray
        Tube diameter, twice `a` [m].
    bendRadius : float or np.ndarray
        Distance from the axis of revolution to the tube centre [m].

    Returns:
    --------
    float or np.ndarray
        Factor at or above one, and one where no bend radius is given.

    '''

    if bendRadius is None:
        return 1.0

    a = np.asarray(diameter, dtype = float)/2.0
    bend = np.asarray(bendRadius, dtype = float)

    # A tube as wide as its own bend has no crotch to speak of, and the closed form runs away
    # there, so the correction is held at the last radius where the shell is still a torus.
    clearance = np.maximum(bend - a, 0.5*a)

    return (2.0*bend - a)/(2.0*clearance)

def hoopStressCalculator(pressureDifferential: float, diameter: float, thickness: float = None,
                         hoopStress: float = None, bendRadius = None) -> float:

    '''

    Thin wall hoop stress, or the thickness that holds one, for a straight tube or a torus.

    The straight tube relation is

        sigma_h = dP * D / (2 t)

    and a bend radius multiplies it by `toroidalCrotchFactor`, which is what a scroll needs: a
    volute is a torus, and its wall is thinnest relative to its load where the tube faces the axis.

    Parameters:
    -----------
    pressureDifferential : float
        Pressure across the wall [Pa].
    diameter : float
        Tube diameter [m].
    thickness : float, optional
        Wall thickness, to solve for stress [m].
    hoopStress : float, optional
        Allowable stress, to solve for thickness [Pa].
    bendRadius : float, optional
        Distance from the axis of revolution to the tube centre [m]. Omitted, the tube is straight.

    Returns:
    --------
    float
        Stress [Pa] when a thickness was given, thickness [m] when a stress was given.

    Raises:
    -------
    ValueError
        Unless exactly one of `thickness` and `hoopStress` is given.

    '''

    if (thickness is None) == (hoopStress is None):
        raise ValueError('hoopStressCalculator needs exactly one of thickness and hoopStress: '
                         'the other is what it solves for.')

    factor = toroidalCrotchFactor(diameter, bendRadius)

    if hoopStress is None:
        return (pressureDifferential * diameter) * factor / (2 * thickness)

    return (pressureDifferential * diameter) * factor / (2 * hoopStress)

class Volute:

    '''
    
    Class definition for generating generalized volute geometry.

    '''

    #-----------------------------------------------------------------#
    # -- Default values for volute object -- #
    #-----------------------------------------------------------------#

    def __init__(self,
                 voluteScrollRadius:            float = 10,
                 scrollDirection:               float = 'cw',
                 crossSectionType:              str   = 'circle',
                 numCrossSections:              int   = 100,
                 crossSectionResolution:        int   = 100,
                 axialOffset:                   float = 0,
                 anchorBy:                      str   = 'c',
                 scaledBy:                      str   = 'linear',
                 scrollType:                    str   = 'cutwater',
                 numOrifices:                   int   = None,
                 interfaceArea:                 float = None,
                 interfaceHydraulicDiameter:    float = None,
                 interfaceCharLen:              float = None,
                 expandedArea:                  float = None,
                 expandedHydraulicDiameter:     float = None,
                 expandedCharLen:               float = None,
                 printabilityAngle:             float = 0,
                 circlePrintability:            str   = 'off',
                 wallThickness:                 float = None,
                 minWallThickness:              float = 0.0,
                 wallHoopStress:                float = None,
                 pressureDifferential:          float = None,
                 alignWallBy:                   str   = 'inner',
                 progressbar:                   str   = 'on',
                 export:                        str   = 'off',
                 filename:                      str   = 'volute',
                 outputDirectory:               str   = None):

        # -- Geometry properties of volute object -- #

        # Scroll
        self.voluteScrollRadius     = voluteScrollRadius     # [m]
        self.scrollDirection        = scrollDirection        # 'cw' , 'ccw'
        # Cross sections
        self.crossSectionType       = crossSectionType       # 'circle' , 'squarc'
        self.numCrossSections       = numCrossSections       # [int]
        self.crossSectionResolution = crossSectionResolution # [int]
        # Alignment
        self.axialOffset            = axialOffset            # [m]
        self.anchorBy               = anchorBy               # 'c' , 'n' , 's' , 'i' , 'o' , 'ni' , 'si' , 'no' , 'so'

        # Area Distribution
        self.scaledBy                   = scaledBy                   # 'linear'
        self.scrollType                 = scrollType                 # 'cutwater' , 'ring'
        self.numOrifices                = numOrifices                # [int]
        self.interfaceArea              = interfaceArea              # [m^2]
        self.interfaceHydraulicDiameter = interfaceHydraulicDiameter # [m]
        self.interfaceCharLen           = interfaceCharLen           # [m] characteristic length option used for squarc volutes
        self.expandedArea               = expandedArea               # [m^2]
        self.expandedHydraulicDiameter  = expandedHydraulicDiameter  # [m]
        self.expandedCharLen            = expandedCharLen            # [m] characteristic length option used for squarc volutes

        # Printability criteria
        self.printabilityAngle  = printabilityAngle  # [deg] Angle of geometry with printability concerns
        self.circlePrintability = circlePrintability # 'on' , 'off' flag for interior support wall for circle volute

        # Wall options
        self.wallThickness        = wallThickness        # [m] scalar or vector or None
        self.minWallThickness     = minWallThickness     # [m] floor the sized wall is held at
        self.wallHoopStress       = wallHoopStress       # [Pa]
        self.pressureDifferential = pressureDifferential # [Pa]
        self.alignWallBy          = alignWallBy          # 'inner' , 'outer'

        # -- Program options -- #

        self.progressbar = progressbar # 'on' , 'off'
        self.export      = export      # 'on' , 'off'
        self.filename    = filename    # [str]
        self.outputDirectory = outputDirectory # [str], None writes to the working directory

        # -- Calculated properties -- #
        self.crossSectionalArea = []   # [m^2] area the law asked for at each section
        self.hydraulicDiameter  = []   # [m]   from the area the law asked for
        self.drawnArea          = []   # [m^2] area the drawn polygon encloses
        self.flowArea           = []   # [m^2] drawn area less any support inside the duct
        self.supportArea        = []   # [m^2] area a printability support occupies

        # -- Outputs -- #
        self.xVolute = []
        self.yVolute = []
        self.zVolute = []

        self.xShell = []
        self.yShell = []
        self.zShell = []

        self.xInternalSupportWall        = []
        self.yInternalSupportWall        = []
        self.zInternalSupportWall        = []
        self.xInternalSupportFilletUpper = []
        self.yInternalSupportFilletUpper = []
        self.zInternalSupportFilletUpper = []
        self.xInternalSupportFilletLower = []
        self.yInternalSupportFilletLower = []
        self.zInternalSupportFilletLower = []

    #-----------------------------------------------------------------#
    # -- Public Methods (Methods accessible by users) -- #
    #-----------------------------------------------------------------#

    def generateVolute(self):

        '''
        
        The structure of the volute generator assumes that the relevant properties of the volute
        are pre-defined as a part of instantiating the Volute() class and therefore the generate
        volute method does not require any passed-in variables. It simply exists to execute the
        generation of volute geometry and assign the values in the calculated arrays to your volute
        object.
        
        '''

        import os

        # Where an exported STL is written. Reading it off the launching script's directory put
        # geometry wherever the entry point happened to live, and failed outright in a session
        # with no script behind it, so it is a property of the volute with the working directory
        # as its default.
        outputDirectory = self.outputDirectory or os.getcwd()
        os.makedirs(outputDirectory, exist_ok = True)

        # # Step 1: Make the diffuser
        # self.generateDiffuser()

        # Step 2: Determine the type of volute to create and generate it. A name the generator
        # does not build has to be refused here: returning empty arrays looks like a volute with
        # no geometry in it rather than a cross section that was never drawn.
        family = str(self.crossSectionType).lower()
        checkFamily(family)
        checkScrollType(str(self.scrollType).lower())

        # A support is a shape rather than a flag, so a name that is neither shape nor 'off' asked
        # for something that does not exist and used to draw nothing without saying so.
        support = str(self.circlePrintability).lower()
        if support not in VOLUTEPRINTABILITY:
            raise ValueError(f'circlePrintability must be one of '
                             f'{", ".join(VOLUTEPRINTABILITY)}, not {self.circlePrintability!r}.')

        if str(self.scaledBy).lower() != 'linear':
            raise ValueError("scaledBy must be 'linear'. The area law is linear in wrap angle; no "
                             'other distribution is implemented.')

        # The overhang support is drawn from a circular wall, so it has no squircle form: its
        # fillets are found by intersecting the support against a circular arc, which on a
        # squircle's straight faces has no solution.
        if family != 'circle' and str(self.circlePrintability).lower() in ('thick', 'thin'):
            raise ValueError(f'A printability support is drawn for a circular cross section only, '
                             f'not for {family!r}. Draw the section as a circle, or leave the '
                             f'support off.')

        match family:
            case 'circle':
                self.generateCircleVolute()
            case 'squarc':
                self.generateSquarcVolute()

        # Step 3: Record what the swept surface encloses, which is not what the area law asked
        # for: a section is drawn as a polygon inscribed in its own profile, and a support inside
        # the duct takes area back out of it.
        self.drawnArea = sweptSectionAreas(self.xVolute, self.yVolute, self.zVolute)
        self.flowArea = self.drawnArea - np.asarray(self.supportArea, dtype = float) \
            if np.size(self.supportArea) else self.drawnArea

        # Step 4: Export geometry (if user specified)
        if self.export == 'on':

            py2cad(os.path.join(outputDirectory, self.filename + '.stl'), self.xVolute, self.yVolute, self.zVolute)
            if self.wallThickness is not None:
                py2cad(os.path.join(outputDirectory, self.filename + '_eggShell.stl'), self.xShell, self.yShell, self.zShell)
            if self.circlePrintability.lower() == 'thick':
                py2cad(os.path.join(outputDirectory, self.filename + '_internalSupportWall.stl'),        self.xInternalSupportWall, self.yInternalSupportWall, self.zInternalSupportWall)
                py2cad(os.path.join(outputDirectory, self.filename + '_internalSupportFilletUpper.stl'), self.xInternalSupportFilletUpper, self.yInternalSupportFilletUpper, self.zInternalSupportFilletUpper)
                py2cad(os.path.join(outputDirectory, self.filename + '_internalSupportFilletLower.stl'), self.xInternalSupportFilletLower, self.yInternalSupportFilletLower, self.zInternalSupportFilletLower)
            if self.circlePrintability.lower() == 'thin':
                py2cad(os.path.join(outputDirectory, self.filename + '_internalSupportWall.stl'),        self.xInternalSupportWall, self.yInternalSupportWall, self.zInternalSupportWall)
                py2cad(os.path.join(outputDirectory, self.filename + '_internalSupportFilletUpper.stl'), self.xInternalSupportFilletUpper, self.yInternalSupportFilletUpper, self.zInternalSupportFilletUpper)

    def tongueGap(self) -> float:

        '''

        Angle the sweep stops short of a full turn by [rad].

        A ring closes on itself and carries no tongue wall, so it sweeps the full turn. A cutwater
        needs its two ends in different meridional planes with a wall between them, so it stops
        short by the angle that wall occupies at the scroll radius.

        '''

        if str(self.scrollType).lower() == 'ring':
            return 0.0

        return tongueGapAngle(self.voluteScrollRadius, self.wallThickness, self.numCrossSections)

    def generateCircleVolute(self):

        '''
        
        This method generates a circular cross section volute.

        The anchor point can be north, south, inside, outside, combinations thereof, or center.
        Specify the anchor point with one or two letters, e.g. 'n' , 'o' , or 'no'.
        Unspecified, the default is center.
        An invalid anchor point argument will also anchor center.

        Area distribution can be scedified by either hydraulic diameter or CSA on either side,
        or either hydraulic diameter or CSA on one side and number of orifices.

        Printability support enabled
        
        '''

        def drawCircleSupportThick(R):

            # scope inputs
            thetaCirc   = np.linspace(0, 2*np.pi, self.crossSectionResolution)
            yCircleWall = R*np.cos(thetaCirc)
            zCircleWall = R*np.sin(thetaCirc)
            t           = 0.00075        # printability thickness, [m]
            r           = 0.001          # printability fillet radius, [m]
            a           = np.deg2rad(30) # printability angle, [deg]->[rad]

            ## rectilinear wall
            D = R*2.5 # dummy extension length, to be trimmed later
            yRectilinear = np.array([ t/2, +t/2])
            zRectilinear = np.array([-D,     D  ])

            #### upper transition body

            ## rectilinear overhang
            # find where circle wall violates printability
            yOverhangRadial             = np.array([0, D*np.sin(a)])
            zOverhangRadial             = np.array([0, D*np.cos(a)])
            overhangRadialIntersection  = intersection(yOverhangRadial,zOverhangRadial,yCircleWall,zCircleWall)
            yOverhangRadialIntersection = overhangRadialIntersection[0][0][0]
            zOverhangRadialIntersection = overhangRadialIntersection[1][0][0]
            # draw extended linear overhang
            yOverhang = np.array([yOverhangRadialIntersection - D*np.cos(a),yOverhangRadialIntersection + D*np.cos(a)])
            zOverhang = np.array([zOverhangRadialIntersection - D*np.sin(a),zOverhangRadialIntersection + D*np.sin(a)])

            ### fillets
            yOverhangOff, zOverhangOff = parallelOffset(yOverhang,zOverhang,-r)
            ## circle wall fillet
            yCircleWallOff, zCircleWallOff = parallelOffset(yCircleWall,zCircleWall,r)
            # draw circle
            filletCenter1  = intersection(yCircleWallOff,zCircleWallOff,yOverhangOff,zOverhangOff)
            yFilletCenter1 = filletCenter1[0][0][0]
            zFilletCenter1 = filletCenter1[1][0][0]
            yFilletCircle1 = 1.005*r * np.cos(np.linspace(0,2*np.pi,self.crossSectionResolution*2)) + yFilletCenter1
            zFilletCircle1 = 1.005*r * np.sin(np.linspace(0,2*np.pi,self.crossSectionResolution*2)) + zFilletCenter1
            # trim overhang
            overhangIntersections = intersection(yOverhang,zOverhang,yFilletCircle1,zFilletCircle1)
            yOverhangIntersection = overhangIntersections[0][0][0]
            zOverhangIntersection = overhangIntersections[1][0][0]
            yOverhang[-1]         = yOverhangIntersection
            zOverhang[-1]         = zOverhangIntersection
            # trim wall arc
            wallIntersections     = intersection(yCircleWall,zCircleWall,yFilletCircle1,zFilletCircle1)
            yWallIntersection     = wallIntersections[0][-1][0]
            zWallIntersection     = wallIntersections[1][-1][0]
            thetaWallIntersection = np.arctan((zWallIntersection)/(yWallIntersection))
            yArcUpper = (R) * np.cos(np.linspace(thetaWallIntersection,np.pi/2,int(self.crossSectionResolution/4)))
            zArcUpper = (R) * np.sin(np.linspace(thetaWallIntersection,np.pi/2,int(self.crossSectionResolution/4)))
            # trim fillet
            thetaWallIntersection     = np.arctan((zWallIntersection-zFilletCenter1)/(yWallIntersection-yFilletCenter1))
            thetaOverhangIntersection = np.arctan((zOverhangIntersection-zFilletCenter1)/(yFilletCenter1-yOverhangIntersection))
            yFillet1 = (1.005*r) * np.cos(np.linspace(thetaWallIntersection,np.pi-thetaOverhangIntersection,int(self.crossSectionResolution/4))) + yFilletCenter1
            zFillet1 = (1.005*r) * np.sin(np.linspace(thetaWallIntersection,np.pi-thetaOverhangIntersection,int(self.crossSectionResolution/4))) + zFilletCenter1
            ## rectilinear wall fillet
            yRectilinearOff, zRectilinearOff = parallelOffset(yRectilinear,zRectilinear,-r)
            # draw circle
            filletCenter2  = intersection(yRectilinearOff,zRectilinearOff,yOverhangOff,zOverhangOff)
            yFilletCenter2 = filletCenter2 [0][0][0]
            zFilletCenter2 = filletCenter2 [1][0][0]
            yFilletCircle2 = 1.005*r * np.cos(np.linspace(0,2*np.pi,self.crossSectionResolution*2)) + yFilletCenter2
            zFilletCircle2 = 1.005*r * np.sin(np.linspace(0,2*np.pi,self.crossSectionResolution*2)) + zFilletCenter2
            # trim overhang
            overhangIntersections = intersection(yOverhang,zOverhang,yFilletCircle2,zFilletCircle2)
            yOverhangIntersection = overhangIntersections[0][0][0]
            zOverhangIntersection = overhangIntersections[1][0][0]
            yOverhang[0] = yOverhangIntersection
            zOverhang[0] = zOverhangIntersection
            # trim rectilinear
            rectilinearIntersections = intersection(yRectilinear,zRectilinear,yFilletCircle2,zFilletCircle2)
            yRectilinearIntersection = rectilinearIntersections[0][0][0]
            zRectilinearIntersection = rectilinearIntersections[1][0][0]
            yRectilinear[-1] = yRectilinearIntersection
            zRectilinear[-1] = zRectilinearIntersection
            # trim fillet
            thetaWallIntersection     = np.arctan((zRectilinearIntersection-zFilletCenter2)/(yFilletCenter2-yRectilinearIntersection))
            thetaOverhangIntersection = np.arctan((zOverhangIntersection-zFilletCenter2 )/(yFilletCenter2 -yOverhangIntersection))
            yFillet2 = (1.005*r) * np.cos(np.linspace(np.pi-thetaOverhangIntersection,np.pi-thetaWallIntersection,int(self.crossSectionResolution/4))) + yFilletCenter2
            zFillet2 = (1.005*r) * np.sin(np.linspace(np.pi-thetaOverhangIntersection,np.pi-thetaWallIntersection,int(self.crossSectionResolution/4))) + zFilletCenter2

            # stitch
            yTransitionBodyQuad1 = np.concatenate([np.flip(yFillet2),np.flip(yFillet1),yArcUpper])
            zTransitionBodyQuad1 = np.concatenate([np.flip(zFillet2),np.flip(zFillet1),zArcUpper+t])
            yTransitionBodyQuad2 = np.flip(-yTransitionBodyQuad1)
            zTransitionBodyQuad2 = np.flip( zTransitionBodyQuad1)
            yTransitionBodyUpper = np.concatenate([yTransitionBodyQuad1,yTransitionBodyQuad2,[yTransitionBodyQuad1[0]]])
            zTransitionBodyUpper = np.concatenate([zTransitionBodyQuad1,zTransitionBodyQuad2,[zTransitionBodyQuad1[0]]])

            #### lower transition body

            ## fillet
            # draw circle
            zRectilinearOff[-1] = 0
            filletCenter3  = intersection(yCircleWallOff,zCircleWallOff,yRectilinearOff,zRectilinearOff)
            yFilletCenter3 = filletCenter3[0][0][0]
            zFilletCenter3 = filletCenter3[1][0][0]
            yFilletCircle3 = 1.001*r * np.cos(np.linspace(0,2*np.pi,self.crossSectionResolution*2)) + yFilletCenter3
            zFilletCircle3 = 1.001*r * np.sin(np.linspace(0,2*np.pi,self.crossSectionResolution*2)) + zFilletCenter3
            # trim rectilinear
            zRectilinearIntersection = zFilletCenter3
            zRectilinear[0] = zRectilinearIntersection
            # trim wall arc
            wallIntersections     = intersection(yCircleWall,zCircleWall,yFilletCircle3,zFilletCircle3)
            yWallIntersection     = wallIntersections[0][-1][0]
            zWallIntersection     = wallIntersections[1][-1][0]
            thetaWallIntersection = np.arctan((yWallIntersection)/(-zWallIntersection))
            yArcLower = (R) * np.cos(np.linspace((3*np.pi/2),(3*np.pi/2)+thetaWallIntersection,int(self.crossSectionResolution/4)))
            zArcLower = (R) * np.sin(np.linspace((3*np.pi/2),(3*np.pi/2)+thetaWallIntersection,int(self.crossSectionResolution/4)))
            # trim fillet
            thetaWallIntersection = np.arctan((yWallIntersection-yFilletCenter3)/(zFilletCenter3-zWallIntersection))
            yFillet3 = (1.001*r) * np.cos(np.linspace(np.pi,(3*np.pi/2)+thetaWallIntersection,int(self.crossSectionResolution/4))) + yFilletCenter3
            zFillet3 = (1.001*r) * np.sin(np.linspace(np.pi,(3*np.pi/2)+thetaWallIntersection,int(self.crossSectionResolution/4))) + zFilletCenter3

            # stitch
            yTransitionBodyQuad4 = np.concatenate([yFillet3,np.flip(yArcLower)])
            zTransitionBodyQuad4 = np.concatenate([zFillet3,np.flip(zArcLower-t)])
            yTransitionBodyQuad3 = np.flip(-yTransitionBodyQuad4)
            zTransitionBodyQuad3 = np.flip( zTransitionBodyQuad4)
            yTransitionBodyLower = np.concatenate([yTransitionBodyQuad4,yTransitionBodyQuad3,[yTransitionBodyQuad4[0]]])
            zTransitionBodyLower = np.concatenate([zTransitionBodyQuad4,zTransitionBodyQuad3,[zTransitionBodyQuad4[0]]])

            ## lattice wall
            yLatticeWall = np.array([ yRectilinear[-1],     (-yRectilinear[-1] ),   (-yRectilinear[-1] ),   yRectilinear[-1],     yRectilinear[-1]     ])
            zLatticeWall = np.array([(zRectilinear[-1] + t),( zRectilinear[-1] + t),( zRectilinear[0] - t),(zRectilinear[0] - t),(zRectilinear[-1] + t)])

            ## store
            xInternalSupportWallCS        = np.zeros((5))
            yInternalSupportWallCS        = yLatticeWall
            zInternalSupportWallCS        = zLatticeWall
            xInternalSupportFilletUpperCS = np.zeros((int(1.5*self.crossSectionResolution+1)))
            yInternalSupportFilletUpperCS = yTransitionBodyUpper
            zInternalSupportFilletUpperCS = zTransitionBodyUpper
            xInternalSupportFilletLowerCS = np.zeros((int(self.crossSectionResolution+1)))
            yInternalSupportFilletLowerCS = yTransitionBodyLower
            zInternalSupportFilletLowerCS = zTransitionBodyLower

            ## area caulculation
            # upper fillet
            yTransitionBodyQuad1 = np.concatenate([np.flip(yFillet2),np.flip(yFillet1),yArcUpper])
            zTransitionBodyQuad1 = np.concatenate([np.flip(zFillet2),np.flip(zFillet1),zArcUpper])
            yTransitionBodyQuad2 = np.flip(-yTransitionBodyQuad1)
            zTransitionBodyQuad2 = np.flip( zTransitionBodyQuad1)
            yTransitionBodyUpperNoOverlap = np.concatenate([yTransitionBodyQuad1,yTransitionBodyQuad2,[yTransitionBodyQuad1[0]]])
            zTransitionBodyUpperNoOverlap = np.concatenate([zTransitionBodyQuad1,zTransitionBodyQuad2,[zTransitionBodyQuad1[0]]])
            # lower fillet
            yTransitionBodyQuad4 = np.concatenate([yFillet3,np.flip(yArcLower)])
            zTransitionBodyQuad4 = np.concatenate([zFillet3,np.flip(zArcLower)])
            yTransitionBodyQuad3 = np.flip(-yTransitionBodyQuad4)
            zTransitionBodyQuad3 = np.flip( zTransitionBodyQuad4)
            yTransitionBodyLowerNoOverlap = np.concatenate([yTransitionBodyQuad4,yTransitionBodyQuad3,[yTransitionBodyQuad4[0]]])
            zTransitionBodyLowerNoOverlap = np.concatenate([zTransitionBodyQuad4,zTransitionBodyQuad3,[zTransitionBodyQuad4[0]]])
            # lattice wall
            yLatticeWallNoOverlap = np.array([yRectilinear[-1],-yRectilinear[-1],-yRectilinear[-1],yRectilinear[-1],yRectilinear[-1]])
            zLatticeWallNoOverlap = np.array([zRectilinear[-1], zRectilinear[-1], zRectilinear[0], zRectilinear[0], zRectilinear[-1]])
            # trapazoidal integration
            supportArea = abs(np.trapezoid(zTransitionBodyLowerNoOverlap,yTransitionBodyLowerNoOverlap)) + \
                abs(np.trapezoid(zTransitionBodyUpperNoOverlap,yTransitionBodyUpperNoOverlap)) + \
                    abs(np.trapezoid(zLatticeWallNoOverlap,yLatticeWallNoOverlap))

            # # Debug plot
            # plt.figure()
            # plt.plot(yCircleWall,zCircleWall,'k',linewidth=2)
            # plt.plot([0,0],
            #          [0.5*D, 0.5*D],'dimgrey',linestyle=':')
            # plt.plot(yTransitionBodyUpper,zTransitionBodyUpper,'m',linewidth=2)
            # plt.plot(yTransitionBodyLower,zTransitionBodyLower,'m',linewidth=2)
            # plt.plot(yLatticeWall,zLatticeWall,'c',linewidth=2)
            # plt.plot(yTransitionBodyUpperNoOverlap,zTransitionBodyUpperNoOverlap,'r',linewidth=2)
            # plt.plot(yTransitionBodyLowerNoOverlap,zTransitionBodyLowerNoOverlap,'r',linewidth=2)
            # plt.plot(yLatticeWallNoOverlap,zLatticeWallNoOverlap,'r',linewidth=2)
            # plt.axis('equal')
            # plt.show(block = True)

            return xInternalSupportWallCS,       yInternalSupportWallCS,       zInternalSupportWallCS,\
                    xInternalSupportFilletUpperCS,yInternalSupportFilletUpperCS,zInternalSupportFilletUpperCS,\
                    xInternalSupportFilletLowerCS,yInternalSupportFilletLowerCS,zInternalSupportFilletLowerCS,\
                    supportArea

        def drawCircleSupportThin(R):

            # scope inputs
            thetaCirc   = np.linspace(0, 2*np.pi, self.crossSectionResolution)
            yCircleWall = R*np.cos(thetaCirc)
            zCircleWall = R*np.sin(thetaCirc)
            t           = 0.00075        # printability thickness, [m]
            r           = 0.001          # printability fillet radius, [m]
            a           = np.deg2rad(30) # printability angle, [deg]->[rad]

            ## upper fillet
            # arc
            thetaArc = np.linspace(0.5*np.pi - a, 0.5*np.pi + a, self.crossSectionResolution - 4)
            yArc = R * np.cos(thetaArc)
            zArc = R * np.sin(thetaArc) + t
            # tri
            triUpperRight = [R * np.cos(0.5*np.pi - a), R*np.sin(0.5*np.pi - a)]
            triUpperLeft  = [R * np.cos(0.5*np.pi + a), R*np.sin(0.5*np.pi + a)]
            dely = R *    np.sin(a)
            delz = dely * np.tan(a)
            triCenter = [triUpperRight[0] - dely, triUpperRight[1] - delz]
            yTri = [triUpperLeft[0],triCenter[0],triUpperRight[0]]
            zTri = [triUpperLeft[1],triCenter[1],triUpperRight[1]]
            # stitch
            xInternalSupportFilletUpperCS = np.zeros((self.crossSectionResolution))
            yInternalSupportFilletUpperCS = np.concatenate([yArc,yTri,[yArc[0]]])
            zInternalSupportFilletUpperCS = np.concatenate([zArc,zTri,[zArc[0]]])

            ## sheet
            xInternalSupportWallCS = [0,0]
            yInternalSupportWallCS = [0,0]
            zInternalSupportWallCS = [-R,triCenter[1]]

            # # Debug plot
            # plt.figure()
            # plt.plot(yCircleWall,zCircleWall,'k',linewidth = 2)
            # plt.plot(yInternalSupportFilletUpperCS,zInternalSupportFilletUpperCS,'c',linewidth = 3)
            # plt.plot(yInternalSupportWallCS,zInternalSupportWallCS,'m',linewidth = 3)
            # plt.axis('equal')
            # plt.show(block = True)
            # debug = 1

            supportArea = np.abs(np.trapezoid(zInternalSupportFilletUpperCS,yInternalSupportFilletUpperCS)) + 0.002*abs(zInternalSupportWallCS[0]-zInternalSupportWallCS[1])

            return xInternalSupportWallCS,       yInternalSupportWallCS,       zInternalSupportWallCS,\
                    xInternalSupportFilletUpperCS,yInternalSupportFilletUpperCS,zInternalSupportFilletUpperCS,\
                    supportArea

        ## Define area distribution
        scroll = resolveScrollAreas(str(self.crossSectionType).lower(),
                                    interfaceArea = self.interfaceArea,
                                    interfaceHydraulicDiameter = self.interfaceHydraulicDiameter,
                                    interfaceCharacteristicLength = self.interfaceCharLen,
                                    expandedArea = self.expandedArea,
                                    expandedHydraulicDiameter = self.expandedHydraulicDiameter,
                                    expandedCharacteristicLength = self.expandedCharLen,
                                    numOrifices = self.numOrifices)
        self.interfaceArea              = scroll['interfaceArea']
        self.expandedArea               = scroll['expandedArea']
        self.interfaceHydraulicDiameter = scroll['interfaceHydraulicDiameter']
        self.expandedHydraulicDiameter  = scroll['expandedHydraulicDiameter']
        self.numOrifices                = scroll['numOrifices']

        self.crossSectionalArea = scrollAreaDistribution(self.interfaceArea, self.expandedArea,
                                                         self.numCrossSections,
                                                         str(self.scrollType).lower())
        self.hydraulicDiameter  = sectionHydraulicDiameter('circle', self.crossSectionalArea)
        radiusDistribution      = self.hydraulicDiameter/2

        ## generate inner wall CSs with center at (0,0):
        # preallocate
        xCS, yCS, zCS = [np.zeros((self.numCrossSections,self.crossSectionResolution)) for _ in range(3)]
        if self.circlePrintability.lower() == 'thick':
            xInternalSupportWallCS,yInternalSupportWallCS,zInternalSupportWallCS = \
                [np.zeros((self.numCrossSections,5)) for _ in range(3)]
            xInternalSupportFilletUpperCS,yInternalSupportFilletUpperCS,zInternalSupportFilletUpperCS = \
                [np.zeros((self.numCrossSections,int(1.5*self.crossSectionResolution+1))) for _ in range(3)]
            xInternalSupportFilletLowerCS,yInternalSupportFilletLowerCS,zInternalSupportFilletLowerCS = \
                [np.zeros((self.numCrossSections,int(self.crossSectionResolution+1))) for _ in range(3)]
        if self.circlePrintability.lower() == 'thin':
            xInternalSupportWallCS,yInternalSupportWallCS,zInternalSupportWallCS = \
                [np.zeros((self.numCrossSections,2)) for _ in range(3)]
            xInternalSupportFilletUpperCS,yInternalSupportFilletUpperCS,zInternalSupportFilletUpperCS = \
                [np.zeros((self.numCrossSections,self.crossSectionResolution)) for _ in range(3)]
        thetaCirc = np.linspace(0, 2*np.pi, self.crossSectionResolution)
        counter = np.zeros((self.numCrossSections))
        supportAreaDistribution = np.zeros((self.numCrossSections))
        # loop
        if str(self.progressbar).lower() == 'on':
            print('Generating Volute Cross Sections:')
        for i in tqdm(range(self.numCrossSections), disable = str(self.progressbar).lower() != 'on'):

            R = radiusDistribution[i]
            yCS[i,:] = R*np.cos(thetaCirc)
            zCS[i,:] = R*np.sin(thetaCirc)

            # draw circle support
            if self.circlePrintability.lower() == 'thick':

                xInternalSupportWallCS[i,:],       yInternalSupportWallCS[i,:],       zInternalSupportWallCS[i,:],       \
                xInternalSupportFilletUpperCS[i,:],yInternalSupportFilletUpperCS[i,:],zInternalSupportFilletUpperCS[i,:],\
                xInternalSupportFilletLowerCS[i,:],yInternalSupportFilletLowerCS[i,:],zInternalSupportFilletLowerCS[i,:],\
                supportArea = drawCircleSupportThick(R)

                nominalArea = np.pi*(R**2)
                usableArea = nominalArea - supportArea
                while usableArea < self.crossSectionalArea[i]: # area correction convergence loop
                    counter[i] += 1
                    R *= 1.001
                    yCS[i,:] = R*np.cos(thetaCirc)
                    zCS[i,:] = R*np.sin(thetaCirc)

                    # draw circle support
                    xInternalSupportWallCS[i,:],       yInternalSupportWallCS[i,:],       zInternalSupportWallCS[i,:],       \
                    xInternalSupportFilletUpperCS[i,:],yInternalSupportFilletUpperCS[i,:],zInternalSupportFilletUpperCS[i,:],\
                    xInternalSupportFilletLowerCS[i,:],yInternalSupportFilletLowerCS[i,:],zInternalSupportFilletLowerCS[i,:],\
                    supportArea = drawCircleSupportThick(R)

                    nominalArea = np.pi*(R**2)
                    usableArea  = nominalArea - supportArea

                radiusDistribution[i] = R
                supportAreaDistribution[i] = supportArea

            if self.circlePrintability.lower() == 'thin':

                xInternalSupportWallCS[i,:],       yInternalSupportWallCS[i,:],       zInternalSupportWallCS[i,:],       \
                xInternalSupportFilletUpperCS[i,:],yInternalSupportFilletUpperCS[i,:],zInternalSupportFilletUpperCS[i,:],\
                supportArea = drawCircleSupportThin(R)

                nominalArea = np.pi*(R**2)
                usableArea = nominalArea - supportArea
                while usableArea < self.crossSectionalArea[i]: # area correction convergence loop
                    counter[i] += 1
                    R *= 1.001
                    yCS[i,:] = R*np.cos(thetaCirc)
                    zCS[i,:] = R*np.sin(thetaCirc)

                    # draw circle support
                    xInternalSupportWallCS[i,:],       yInternalSupportWallCS[i,:],       zInternalSupportWallCS[i,:],       \
                    xInternalSupportFilletUpperCS[i,:],yInternalSupportFilletUpperCS[i,:],zInternalSupportFilletUpperCS[i,:],\
                    supportArea = drawCircleSupportThin(R)

                    nominalArea = np.pi*(R**2)
                    usableArea  = nominalArea - supportArea

                radiusDistribution[i] = R

            # move to anchor point
            dy, dz = anchorOffset(self.anchorBy, R)
            yCS[i,:]                           += dy
            zCS[i,:]                           += dz
            if self.circlePrintability.lower() == 'thick':
                yInternalSupportWallCS[i,:]        += dy
                yInternalSupportFilletUpperCS[i,:] += dy
                yInternalSupportFilletLowerCS[i,:] += dy
                zInternalSupportWallCS[i,:]        += dz
                zInternalSupportFilletUpperCS[i,:] += dz
                zInternalSupportFilletLowerCS[i,:] += dz
            if self.circlePrintability.lower() == 'thin':
                yInternalSupportWallCS[i,:]        += dy
                yInternalSupportFilletUpperCS[i,:] += dy
                zInternalSupportWallCS[i,:]        += dz
                zInternalSupportFilletUpperCS[i,:] += dz

        # update values to refelct circle cupport area corrections
        self.supportArea        = supportAreaDistribution
        self.hydraulicDiameter  = radiusDistribution*2
        self.crossSectionalArea = np.pi*(radiusDistribution**2)

        # generate shell
        if self.wallThickness is not None or self.wallHoopStress is not None:
            # Each section is a tube on its own bend radius, the radius of its centre, which is
            # where the toroidal correction to the hoop stress comes from.
            bendRadius = self.voluteScrollRadius + np.array(
                [anchorOffset(self.anchorBy, R)[0] for R in radiusDistribution])
            yShellCS, zShellCS, _, _, wallThickness= dynamicEggShell(yCS,zCS,
                                                        self.wallThickness,
                                                        self.wallHoopStress, self.pressureDifferential, self.hydraulicDiameter,
                                                        bendRadius, self.minWallThickness)
            self.wallThickness = wallThickness
            xShellCS = np.zeros_like(xCS)
            # catch inverted wall
            if abs(np.trapezoid(yShellCS[0,:],zShellCS[0,:])) < abs(np.trapezoid(yCS[0,:],zCS[0,:])):
                self.wallThickness *= -1
                yShellCS, zShellCS, _, _, wallThickness= dynamicEggShell(yCS,zCS,
                                                        self.wallThickness)
            self.wallThickness = abs(wallThickness)

        # move cross sections to correct radius
        if self.alignWallBy == 'inner':
            yCS += self.voluteScrollRadius
            if self.wallThickness is not None:
                yShellCS += self.voluteScrollRadius
            if self.circlePrintability.lower() ==  'thick':
                yInternalSupportWallCS += self.voluteScrollRadius
                yInternalSupportFilletUpperCS += self.voluteScrollRadius
                yInternalSupportFilletLowerCS += self.voluteScrollRadius
            if self.circlePrintability.lower() ==  'thin':
                yInternalSupportWallCS += self.voluteScrollRadius
                yInternalSupportFilletUpperCS += self.voluteScrollRadius
        elif self.alignWallBy == 'outer':

            if self.wallThickness is None:
                print('No outer wall to align by.')
                yCS += self.voluteScrollRadius
                if self.wallThickness is not None:
                    yShellCS += self.voluteScrollRadius
                if self.circlePrintability.lower() ==  'thick':
                    yInternalSupportWallCS += self.voluteScrollRadius
                    yInternalSupportFilletUpperCS += self.voluteScrollRadius
                    yInternalSupportFilletLowerCS += self.voluteScrollRadius
                if self.circlePrintability.lower() ==  'thin':
                    yInternalSupportWallCS += self.voluteScrollRadius
                    yInternalSupportFilletUpperCS += self.voluteScrollRadius

            elif self.wallThickness is not None:
                y1p = np.zeros((self.numCrossSections))
                z1p = np.zeros((self.numCrossSections))
                match self.anchorBy.lower():
                    case 'n':
                        z1p += self.wallThickness
                    case 's':
                        z1p -= self.wallThickness
                    case 'o':
                        y1p += self.wallThickness
                    case 'i':
                        y1p -= self.wallThickness
                    case 'no':
                        y1p += self.wallThickness/np.sqrt(2)
                        z1p += self.wallThickness/np.sqrt(2)
                    case 'so':
                        y1p += self.wallThickness/np.sqrt(2)
                        z1p -= self.wallThickness/np.sqrt(2)
                    case 'ni':
                        y1p -= self.wallThickness/np.sqrt(2)
                        z1p += self.wallThickness/np.sqrt(2)
                    case 'si':
                        y1p -= self.wallThickness/np.sqrt(2)
                        z1p -= self.wallThickness/np.sqrt(2)
                for i in range(self.numCrossSections):
                    yCS[i,:] += self.voluteScrollRadius - y1p[i]
                    zCS[i,:] += -z1p[i]
                    yShellCS[i,:] += self.voluteScrollRadius - y1p[i]
                    zShellCS[i,:] += -z1p[i]
                    if self.circlePrintability.lower() ==  'thick':
                        yInternalSupportWallCS[i,:]        += self.voluteScrollRadius - y1p[i]
                        zInternalSupportWallCS[i,:]        += -z1p[i]
                        yInternalSupportFilletUpperCS[i,:] += self.voluteScrollRadius - y1p[i]
                        zInternalSupportFilletUpperCS[i,:] += -z1p[i]
                        yInternalSupportFilletLowerCS[i,:] += self.voluteScrollRadius - y1p[i]
                        zInternalSupportFilletLowerCS[i,:] += -z1p[i]
                    if self.circlePrintability.lower() ==  'thin':
                        yInternalSupportWallCS[i,:]        += self.voluteScrollRadius - y1p[i]
                        zInternalSupportWallCS[i,:]        += -z1p[i]
                        yInternalSupportFilletUpperCS[i,:] += self.voluteScrollRadius - y1p[i]
                        zInternalSupportFilletUpperCS[i,:] += -z1p[i]
        else:
            raise Exception('Invalid wall alignment argument. Please specify inner or outer.')

        # roll cross sections about scroll axis to create mesh
        sweep = 2*np.pi - self.tongueGap()
        if self.scrollDirection.lower() == 'cw':
            rollAngle = np.linspace(0, sweep, self.numCrossSections)
        elif self.scrollDirection.lower() == 'ccw':
            rollAngle = np.linspace(sweep, 0, self.numCrossSections)
        else:
            raise Exception('Invalid scroll direction argument. Please specify cw or ccw.')
        xVolute, yVolute, zVolute = [np.zeros((self.numCrossSections,self.crossSectionResolution)) for _ in range(3)]
        rollAboutAxis(rollAngle, (xCS, yCS, zCS),
                      (xVolute, yVolute, zVolute))

        # roll outer wall cross sections about scroll axis to create mesh
        if self.wallThickness is not None:
            xShell, yShell, zShell = [np.zeros((self.numCrossSections,self.crossSectionResolution)) for _ in range(3)]
            rollAboutAxis(rollAngle, (xShellCS, yShellCS, zShellCS),
                          (xShell, yShell, zShell))

        # roll inner support cross sections about scroll axis to create mesh
        if self.circlePrintability.lower() == 'thick':
            xInternalSupportWall, yInternalSupportWall, zInternalSupportWall =                      \
                [np.zeros((self.numCrossSections,5)) for _ in range(3)]
            xInternalSupportFilletUpper, yInternalSupportFilletUpper, zInternalSupportFilletUpper = \
                [np.zeros((self.numCrossSections,int(1.5*self.crossSectionResolution+1))) for _ in range(3)]
            xInternalSupportFilletLower, yInternalSupportFilletLower, zInternalSupportFilletLower = \
                [np.zeros((self.numCrossSections,int(self.crossSectionResolution+1))) for _ in range(3)]
            rollAboutAxis(rollAngle, (xInternalSupportWallCS, yInternalSupportWallCS, zInternalSupportWallCS),
                          (xInternalSupportWall, yInternalSupportWall, zInternalSupportWall))
            rollAboutAxis(rollAngle, (xInternalSupportFilletUpperCS, yInternalSupportFilletUpperCS, zInternalSupportFilletUpperCS),
                          (xInternalSupportFilletUpper, yInternalSupportFilletUpper, zInternalSupportFilletUpper))
            rollAboutAxis(rollAngle, (xInternalSupportFilletLowerCS, yInternalSupportFilletLowerCS, zInternalSupportFilletLowerCS),
                          (xInternalSupportFilletLower, yInternalSupportFilletLower, zInternalSupportFilletLower))
        if self.circlePrintability.lower() == 'thin':
            xInternalSupportWall, yInternalSupportWall, zInternalSupportWall =                      \
                [np.zeros((self.numCrossSections,2)) for _ in range(3)]
            xInternalSupportFilletUpper, yInternalSupportFilletUpper, zInternalSupportFilletUpper = \
                [np.zeros((self.numCrossSections,self.crossSectionResolution)) for _ in range(3)]
            rollAboutAxis(rollAngle, (xInternalSupportWallCS, yInternalSupportWallCS, zInternalSupportWallCS),
                          (xInternalSupportWall, yInternalSupportWall, zInternalSupportWall))
            rollAboutAxis(rollAngle, (xInternalSupportFilletUpperCS, yInternalSupportFilletUpperCS, zInternalSupportFilletUpperCS),
                          (xInternalSupportFilletUpper, yInternalSupportFilletUpper, zInternalSupportFilletUpper))

        # axial location
        zVolute += self.axialOffset
        if self.wallThickness is not None:
            zShell += self.axialOffset
        if self.circlePrintability.lower() == 'thick':
            zInternalSupportWall        += self.axialOffset
            zInternalSupportFilletUpper += self.axialOffset
            zInternalSupportFilletLower += self.axialOffset
        if self.circlePrintability.lower() == 'thin':
            zInternalSupportWall        += self.axialOffset
            zInternalSupportFilletUpper += self.axialOffset

        # assign
        self.xVolute = xVolute
        self.yVolute = yVolute
        self.zVolute = zVolute
        if self.wallThickness is not None:
            self.xShell = xShell
            self.yShell = yShell
            self.zShell = zShell
        if self.circlePrintability.lower() == 'thick':
            self.xInternalSupportWall        = xInternalSupportWall
            self.yInternalSupportWall        = yInternalSupportWall
            self.zInternalSupportWall        = zInternalSupportWall
            self.xInternalSupportFilletUpper = xInternalSupportFilletUpper
            self.yInternalSupportFilletUpper = yInternalSupportFilletUpper
            self.zInternalSupportFilletUpper = zInternalSupportFilletUpper
            self.xInternalSupportFilletLower = xInternalSupportFilletLower
            self.yInternalSupportFilletLower = yInternalSupportFilletLower
            self.zInternalSupportFilletLower = zInternalSupportFilletLower
        if self.circlePrintability.lower() == 'thin':
            self.xInternalSupportWall        = xInternalSupportWall
            self.yInternalSupportWall        = yInternalSupportWall
            self.zInternalSupportWall        = zInternalSupportWall
            self.xInternalSupportFilletUpper = xInternalSupportFilletUpper
            self.yInternalSupportFilletUpper = yInternalSupportFilletUpper
            self.zInternalSupportFilletUpper = zInternalSupportFilletUpper

    def generateSquarcVolute(self):

        '''
        
        get squarcked, idiot.

        This cross section is a circle squared off at the upper inner corner.
        The printability angle is defined relative to horizontal (XY plane, plane of the scroll)
        The printability angle is maintained as the radius of the arc changes.

        The area distribution can be bounded either by hydraulic diameter or CSA on
        both the interface and expanded sides, or either hydraulic diameter or CSA on one side
        and number of orifices.

        '''

        def drawCircleSupportThick(R):

            # scope inputs
            thetaCirc   = np.linspace(0, 2*np.pi, self.crossSectionResolution*4)
            yCircleWall = R*np.cos(thetaCirc)
            zCircleWall = R*np.sin(thetaCirc)
            t           = 0.00075        # printability thickness, [m]
            r           = 0.001          # printability fillet radius, [m]
            a           = np.deg2rad(30) # printability angle, [deg]->[rad]

            ## rectilinear wall
            D = 2*R # dummy extension length, to be trimmed later
            yRectilinear = np.array([ t/2, t/2])
            zRectilinear = np.array([-D,   D  ])

            #### upper transition body

            ## rectilinear overhang
            # find where circle wall violates printability
            yOverhangRadial             = np.array([0, D*np.sin(a)])
            zOverhangRadial             = np.array([0, D*np.cos(a)])
            overhangRadialIntersection  = intersection(yOverhangRadial,zOverhangRadial,yCircleWall,zCircleWall)
            yOverhangRadialIntersection = overhangRadialIntersection[0][0][0]
            zOverhangRadialIntersection = overhangRadialIntersection[1][0][0]
            # draw extended linear overhang
            yOverhang = np.array([yOverhangRadialIntersection - D*np.cos(a),yOverhangRadialIntersection + D*np.cos(a)])
            zOverhang = np.array([zOverhangRadialIntersection - D*np.sin(a),zOverhangRadialIntersection + D*np.sin(a)])

            ### fillets
            yOverhangOff, zOverhangOff = parallelOffset(yOverhang,zOverhang,-r)
            ## circle wall fillet
            yCircleWallOff, zCircleWallOff = parallelOffset(yCircleWall,zCircleWall,r)
            # draw circle
            filletCenter1  = intersection(yCircleWallOff,zCircleWallOff,yOverhangOff,zOverhangOff)
            yFilletCenter1 = filletCenter1[0][0][0]
            zFilletCenter1 = filletCenter1[1][0][0]
            yFilletCircle1 = 1.005*r * np.cos(np.linspace(0,2*np.pi,self.crossSectionResolution*4)) + yFilletCenter1
            zFilletCircle1 = 1.005*r * np.sin(np.linspace(0,2*np.pi,self.crossSectionResolution*4)) + zFilletCenter1
            # trim overhang
            overhangIntersections = intersection(yOverhang,zOverhang,yFilletCircle1,zFilletCircle1)
            yOverhangIntersection = overhangIntersections[0][0][0]
            zOverhangIntersection = overhangIntersections[1][0][0]
            yOverhang[-1]         = yOverhangIntersection
            zOverhang[-1]         = zOverhangIntersection
            # trim wall arc
            wallIntersections     = intersection(yCircleWall,zCircleWall,yFilletCircle1,zFilletCircle1)
            yWallIntersection1     = wallIntersections[0][-1][0]
            zWallIntersection1     = wallIntersections[1][-1][0]
            thetaWallIntersection = np.arctan((zWallIntersection1)/(yWallIntersection1))
            yArcUpper = (L) * np.cos(np.linspace(thetaWallIntersection,np.pi/2,int(self.crossSectionResolution/4)))
            zArcUpper = (L) * np.sin(np.linspace(thetaWallIntersection,np.pi/2,int(self.crossSectionResolution/4)))
            # trim fillet
            thetaWallIntersection     = np.arctan((zWallIntersection1-zFilletCenter1)/(yWallIntersection1-yFilletCenter1))
            thetaOverhangIntersection = np.arctan((zOverhangIntersection-zFilletCenter1)/(yFilletCenter1-yOverhangIntersection))
            yFillet1 = (1.005*r) * np.cos(np.linspace(thetaWallIntersection,np.pi-thetaOverhangIntersection,int(self.crossSectionResolution/4))) + yFilletCenter1
            zFillet1 = (1.005*r) * np.sin(np.linspace(thetaWallIntersection,np.pi-thetaOverhangIntersection,int(self.crossSectionResolution/4))) + zFilletCenter1
            ## rectilinear wall fillet
            yRectilinearOff, zRectilinearOff = parallelOffset(yRectilinear,zRectilinear,-r)
            # draw circle
            filletCenter2  = intersection(yRectilinearOff,zRectilinearOff,yOverhangOff,zOverhangOff)
            yFilletCenter2 = filletCenter2 [0][0][0]
            zFilletCenter2 = filletCenter2 [1][0][0]
            yFilletCircle2 = 1.005*r * np.cos(np.linspace(0,2*np.pi,self.crossSectionResolution*4)) + yFilletCenter2
            zFilletCircle2 = 1.005*r * np.sin(np.linspace(0,2*np.pi,self.crossSectionResolution*4)) + zFilletCenter2
            # trim overhang
            overhangIntersections = intersection(yOverhang,zOverhang,yFilletCircle2,zFilletCircle2)
            yOverhangIntersection = overhangIntersections[0][0][0]
            zOverhangIntersection = overhangIntersections[1][0][0]
            yOverhang[0] = yOverhangIntersection
            zOverhang[0] = zOverhangIntersection
            # trim rectilinear
            rectilinearIntersections = intersection(yRectilinear,zRectilinear,yFilletCircle2,zFilletCircle2)
            yRectilinearIntersection = rectilinearIntersections[0][0][0]
            zRectilinearIntersection = rectilinearIntersections[1][0][0]
            yRectilinear[-1] = yRectilinearIntersection
            zRectilinear[-1] = zRectilinearIntersection
            # trim fillet
            thetaWallIntersection     = np.arctan((zRectilinearIntersection-zFilletCenter2)/(yFilletCenter2-yRectilinearIntersection))
            thetaOverhangIntersection = np.arctan((zOverhangIntersection-zFilletCenter2 )/(yFilletCenter2 -yOverhangIntersection))
            yFillet2 = (1.005*r) * np.cos(np.linspace(np.pi-thetaOverhangIntersection,np.pi-thetaWallIntersection,int(self.crossSectionResolution/4))) + yFilletCenter2
            zFillet2 = (1.005*r) * np.sin(np.linspace(np.pi-thetaOverhangIntersection,np.pi-thetaWallIntersection,int(self.crossSectionResolution/4))) + zFilletCenter2
            # stitch
            yTransitionBodyQuad1 = np.concatenate([np.flip(yFillet2),np.flip(yFillet1),yArcUpper])
            zTransitionBodyQuad1 = np.concatenate([np.flip(zFillet2),np.flip(zFillet1),zArcUpper+t])
            yTransitionBodyQuad2 = np.flip(-yTransitionBodyQuad1)
            zTransitionBodyQuad2 = np.flip( zTransitionBodyQuad1)
            yTransitionBodyUpper = np.concatenate([yTransitionBodyQuad1,yTransitionBodyQuad2,[yTransitionBodyQuad1[0]]])
            zTransitionBodyUpper = np.concatenate([zTransitionBodyQuad1,zTransitionBodyQuad2,[zTransitionBodyQuad1[0]]])

            #### lower transition body

            ## fillet right
            # draw circle
            zRectilinearOff[-1] = 0
            filletCenter3  = intersection(yCircleWallOff,zCircleWallOff,yRectilinearOff,zRectilinearOff)
            yFilletCenter3 = filletCenter3[0][0][0]
            zFilletCenter3 = filletCenter3[1][0][0]
            yFilletCircle3 = 1.001*r * np.cos(np.linspace(0,2*np.pi,self.crossSectionResolution*2)) + yFilletCenter3
            zFilletCircle3 = 1.001*r * np.sin(np.linspace(0,2*np.pi,self.crossSectionResolution*2)) + zFilletCenter3
            # trim rectilinear
            zRectilinearIntersection = zFilletCenter3
            zRectilinear[0] = zRectilinearIntersection
            # trim wall arc
            wallIntersections     = intersection(yCircleWall,zCircleWall,yFilletCircle3,zFilletCircle3)
            yWallIntersection     = wallIntersections[0][-1][0]
            zWallIntersection     = wallIntersections[1][-1][0]
            thetaWallIntersection = np.arctan((yWallIntersection)/(-zWallIntersection))
            yArcLower = (L) * np.cos(np.linspace((3*np.pi/2),(3*np.pi/2)+thetaWallIntersection,int(self.crossSectionResolution/4)))
            zArcLower = (L) * np.sin(np.linspace((3*np.pi/2),(3*np.pi/2)+thetaWallIntersection,int(self.crossSectionResolution/4)))
            # trim fillet
            thetaWallIntersection = np.arctan((yWallIntersection-yFilletCenter3)/(zFilletCenter3-zWallIntersection))
            yFillet3 = (1.001*r) * np.cos(np.linspace(np.pi,(3*np.pi/2)+thetaWallIntersection,int(self.crossSectionResolution/4))) + yFilletCenter3
            zFillet3 = (1.001*r) * np.sin(np.linspace(np.pi,(3*np.pi/2)+thetaWallIntersection,int(self.crossSectionResolution/4))) + zFilletCenter3
            ## fillet left
            # draw circle
            rL = R-abs(zFilletCenter3)
            yFilletCenterL = -(t/2) - rL
            zFilletCenterL = zFilletCenter3
            # trim fillet
            yFilletL = (1.001*rL) * np.cos(np.linspace(-np.pi/2,0,int(self.crossSectionResolution/4))) + yFilletCenterL
            zFilletL = (1.001*rL) * np.sin(np.linspace(-np.pi/2,0,int(self.crossSectionResolution/4))) + zFilletCenterL
            # stitch
            yTransitionBodyQuad4 = np.concatenate([yFillet3,np.flip(yArcLower)])
            zTransitionBodyQuad4 = np.concatenate([zFillet3,np.flip(zArcLower-t)])
            yTransitionBodyQuad3 = np.concatenate([[yFilletL[0]],yFilletL])
            zTransitionBodyQuad3 = np.concatenate([[-R-t],       zFilletL])
            yTransitionBodyLower = np.concatenate([yTransitionBodyQuad4,yTransitionBodyQuad3,[yTransitionBodyQuad4[0]]])
            zTransitionBodyLower = np.concatenate([zTransitionBodyQuad4,zTransitionBodyQuad3,[zTransitionBodyQuad4[0]]])

            ## lattice wall
            yLatticeWall = np.array([ yRectilinear[-1],     (-yRectilinear[-1] ),   (-yRectilinear[-1] ),   yRectilinear[-1],     yRectilinear[-1]     ])
            zLatticeWall = np.array([(zRectilinear[-1] + t),( zRectilinear[-1] + t),( zRectilinear[0] - t),(zRectilinear[0] - t),(zRectilinear[-1] + t)])

            ## store
            xInternalSupportWallCS        = np.zeros((5))
            yInternalSupportWallCS        = yLatticeWall
            zInternalSupportWallCS        = zLatticeWall
            xInternalSupportFilletUpperCS = np.zeros((int(1.5*self.crossSectionResolution+1)))
            yInternalSupportFilletUpperCS = yTransitionBodyUpper
            zInternalSupportFilletUpperCS = zTransitionBodyUpper
            xInternalSupportFilletLowerCS = np.zeros((int(0.75*self.crossSectionResolution+2)))
            yInternalSupportFilletLowerCS = yTransitionBodyLower
            zInternalSupportFilletLowerCS = zTransitionBodyLower

            ## area caulculation
            # upper fillet
            yTransitionBodyQuad1 = np.concatenate([np.flip(yFillet2),np.flip(yFillet1),yArcUpper])
            zTransitionBodyQuad1 = np.concatenate([np.flip(zFillet2),np.flip(zFillet1),zArcUpper])
            yTransitionBodyQuad2 = np.flip(-yTransitionBodyQuad1)
            zTransitionBodyQuad2 = np.flip( zTransitionBodyQuad1)
            yTransitionBodyUpperNoOverlap = np.concatenate([yTransitionBodyQuad1,yTransitionBodyQuad2,[yTransitionBodyQuad1[0]]])
            zTransitionBodyUpperNoOverlap = np.concatenate([zTransitionBodyQuad1,zTransitionBodyQuad2,[zTransitionBodyQuad1[0]]])
            # lower fillet
            yTransitionBodyQuad4 = np.concatenate([yFillet3,np.flip(yArcLower)])
            zTransitionBodyQuad4 = np.concatenate([zFillet3,np.flip(zArcLower)])
            yTransitionBodyQuad3 = np.concatenate([[yFilletL[0]],yFilletL])
            zTransitionBodyQuad3 = np.concatenate([[zFilletL[0]],zFilletL])
            yTransitionBodyLowerNoOverlap = np.concatenate([yTransitionBodyQuad4,yTransitionBodyQuad3,[yTransitionBodyQuad4[0]]])
            zTransitionBodyLowerNoOverlap = np.concatenate([zTransitionBodyQuad4,zTransitionBodyQuad3,[zTransitionBodyQuad4[0]]])
            # lattice wall
            yLatticeWallNoOverlap = np.array([yRectilinear[-1],-yRectilinear[-1],-yRectilinear[-1],yRectilinear[-1],yRectilinear[-1]])
            zLatticeWallNoOverlap = np.array([zRectilinear[-1], zRectilinear[-1], zRectilinear[0], zRectilinear[0], zRectilinear[-1]])
            # trapazoidal integration
            supportArea = abs(np.trapezoid(zTransitionBodyLowerNoOverlap,yTransitionBodyLowerNoOverlap)) + \
                abs(np.trapezoid(zTransitionBodyUpperNoOverlap,yTransitionBodyUpperNoOverlap)) + \
                    abs(np.trapezoid(zLatticeWallNoOverlap,yLatticeWallNoOverlap))

            # ySquarc = np.concatenate([[-R],R * np.cos(np.linspace(-np.pi/2,np.pi,self.crossSectionResolution)),[-R]])
            # zSquarc = np.concatenate([[-R],R * np.sin(np.linspace(-np.pi/2,np.pi,self.crossSectionResolution)),[-R]])
            # # Debug plot
            # plt.figure()
            # plt.plot(yCircleWall,zCircleWall,'grey',linestyle='--')
            # plt.plot(ySquarc,zSquarc,'k',linewidth=2)
            # plt.plot([0,0],
            #          [0.5*D, 0.5*D],'grey',linestyle=':')
            # plt.plot(yTransitionBodyUpper,zTransitionBodyUpper,'y',linewidth=2)
            # plt.plot(yTransitionBodyLower,zTransitionBodyLower,'m',linewidth=2)
            # plt.plot(yLatticeWall,zLatticeWall,'c',linewidth=2)
            # # plt.plot(yTransitionBodyUpperNoOverlap,zTransitionBodyUpperNoOverlap,'r',linewidth=2)
            # # plt.plot(yTransitionBodyLowerNoOverlap,zTransitionBodyLowerNoOverlap,'r',linewidth=2)
            # # plt.plot(yLatticeWallNoOverlap,zLatticeWallNoOverlap,'r',linewidth=2)
            # plt.plot(yFillet1,zFillet1,'m')
            # plt.plot(yArcUpper,zArcUpper,'b',linewidth=2)
            # plt.scatter([yWallIntersection1],[zWallIntersection1],50,color='m',marker='*')
            # plt.axis('equal')
            # plt.show(block = True)

            return xInternalSupportWallCS,       yInternalSupportWallCS,       zInternalSupportWallCS,\
                   xInternalSupportFilletUpperCS,yInternalSupportFilletUpperCS,zInternalSupportFilletUpperCS,\
                   xInternalSupportFilletLowerCS,yInternalSupportFilletLowerCS,zInternalSupportFilletLowerCS,\
                   supportArea

        def drawCircleSupportThin(R):

            # scope inputs
            thetaCirc   = np.linspace(0, 2*np.pi, self.crossSectionResolution)
            yCircleWall = R*np.cos(thetaCirc)
            zCircleWall = R*np.sin(thetaCirc)
            t           = 0.00075        # printability thickness, [m]
            r           = 0.001          # printability fillet radius, [m]
            a           = np.deg2rad(30) # printability angle, [deg]->[rad]

            ## upper fillet
            # arc
            thetaArc = np.linspace(0.5*np.pi - a, 0.5*np.pi + a, self.crossSectionResolution - 4)
            yArc = R * np.cos(thetaArc)
            zArc = R * np.sin(thetaArc) + t
            # tri
            triUpperRight = [R * np.cos(0.5*np.pi - a), R*np.sin(0.5*np.pi - a)]
            triUpperLeft  = [R * np.cos(0.5*np.pi + a), R*np.sin(0.5*np.pi + a)]
            dely = R *    np.sin(a)
            delz = dely * np.tan(a)
            triCenter = [triUpperRight[0] - dely, triUpperRight[1] - delz]
            yTri = np.concatenate([triUpperLeft[0],triCenter[0],triUpperRight[0]])
            zTri = np.concatenate([triUpperLeft[1],triCenter[1],triUpperRight[1]])
            # stitch
            xInternalSupportFilletUpperCS = np.zeros((self.crossSectionResolution))
            yInternalSupportFilletUpperCS = np.concatenate([yArc,yTri,[yArc[0]]])
            zInternalSupportFilletUpperCS = np.concatenate([zArc,zTri,[zArc[0]]])

            ## sheet
            xInternalSupportWallCS = np.array([0,0])
            yInternalSupportWallCS = np.array([0,0] )
            zInternalSupportWallCS = np.array([-R,triCenter[1]]).reshape(2)

            # # Debug plot
            # plt.figure()
            # plt.plot(yCircleWall,zCircleWall,'k',linewidth = 2)
            # plt.plot(yInternalSupportFilletUpperCS,zInternalSupportFilletUpperCS,'c',linewidth = 3)
            # plt.plot(yInternalSupportWallCS,zInternalSupportWallCS,'m',linewidth = 3)
            # plt.axis('equal')
            # plt.show(block = True)
            # debug = 1

            supportArea = abs(np.trapezoid(zInternalSupportFilletUpperCS,yInternalSupportFilletUpperCS)) + 0.002*abs(zInternalSupportWallCS[0]-zInternalSupportWallCS[1])

            return xInternalSupportWallCS,       yInternalSupportWallCS,       zInternalSupportWallCS,\
                    xInternalSupportFilletUpperCS,yInternalSupportFilletUpperCS,zInternalSupportFilletUpperCS,\
                    supportArea

        ## Define area distribution
        scroll = resolveScrollAreas(str(self.crossSectionType).lower(),
                                    interfaceArea = self.interfaceArea,
                                    interfaceHydraulicDiameter = self.interfaceHydraulicDiameter,
                                    interfaceCharacteristicLength = self.interfaceCharLen,
                                    expandedArea = self.expandedArea,
                                    expandedHydraulicDiameter = self.expandedHydraulicDiameter,
                                    expandedCharacteristicLength = self.expandedCharLen,
                                    numOrifices = self.numOrifices)
        self.interfaceArea              = scroll['interfaceArea']
        self.expandedArea               = scroll['expandedArea']
        self.interfaceHydraulicDiameter = scroll['interfaceHydraulicDiameter']
        self.expandedHydraulicDiameter  = scroll['expandedHydraulicDiameter']
        self.numOrifices                = scroll['numOrifices']

        self.crossSectionalArea = scrollAreaDistribution(self.interfaceArea, self.expandedArea,
                                                         self.numCrossSections,
                                                         str(self.scrollType).lower())
        charLenDistribution     = characteristicLengthFromArea('squarc', self.crossSectionalArea)
        self.hydraulicDiameter  = sectionHydraulicDiameter('squarc', self.crossSectionalArea)

        tiltAngle = -np.deg2rad(self.printabilityAngle)

        ## generate inner wall CSs with corner at (0,0):
        # preallocate
        xCS, yCS, zCS = [np.zeros((self.numCrossSections,self.crossSectionResolution)) for _ in range(3)]
        if self.circlePrintability.lower() == 'thick':
            xInternalSupportWallCS,yInternalSupportWallCS,zInternalSupportWallCS = \
                [np.zeros((self.numCrossSections,5)) for _ in range(3)]
            xInternalSupportFilletUpperCS,yInternalSupportFilletUpperCS,zInternalSupportFilletUpperCS = \
                [np.zeros((self.numCrossSections,int(1.5*self.crossSectionResolution+1))) for _ in range(3)]
            xInternalSupportFilletLowerCS,yInternalSupportFilletLowerCS,zInternalSupportFilletLowerCS = \
                [np.zeros((self.numCrossSections,int(0.75*self.crossSectionResolution+2))) for _ in range(3)]
        if self.circlePrintability.lower() == 'thin':
            xInternalSupportWallCS,yInternalSupportWallCS,zInternalSupportWallCS = \
                [np.zeros((self.numCrossSections,2)) for _ in range(3)]
            xInternalSupportFilletUpperCS,yInternalSupportFilletUpperCS,zInternalSupportFilletUpperCS = \
                [np.zeros((self.numCrossSections,self.crossSectionResolution)) for _ in range(3)]
        thetaCirc = np.linspace(0.5*np.pi + tiltAngle, -np.pi + tiltAngle, self.crossSectionResolution - 2)
        counter = np.zeros((self.numCrossSections))
        # loop
        if str(self.progressbar).lower() == 'on':
            print('Generating Volute Cross Sections:')
        for i in tqdm(range(self.numCrossSections), disable = str(self.progressbar).lower() != 'on'):

            L = charLenDistribution[i]
            yCirc = L*np.sin(thetaCirc) - L*(np.cos(tiltAngle) - np.sin(tiltAngle))
            zCirc = L*np.cos(thetaCirc) + L*(np.cos(tiltAngle) + np.sin(tiltAngle))
            yCSi  = np.concatenate([[0],yCirc,[0]])
            zCSi  = np.concatenate([[0],zCirc,[0]])
            yCS[i,:] = -yCSi
            zCS[i,:] = -zCSi

            # draw circle support
            if self.circlePrintability.lower() == 'thick':

                xInternalSupportWallCS[i,:],       yInternalSupportWallCS[i,:],       zInternalSupportWallCS[i,:],       \
                xInternalSupportFilletUpperCS[i,:],yInternalSupportFilletUpperCS[i,:],zInternalSupportFilletUpperCS[i,:],\
                xInternalSupportFilletLowerCS[i,:],yInternalSupportFilletLowerCS[i,:],zInternalSupportFilletLowerCS[i,:],\
                supportArea = drawCircleSupportThick(L)

                nominalArea = (L**2)*(1+0.75*np.pi)
                usableArea = nominalArea - supportArea
                while usableArea < self.crossSectionalArea[i]:  # area correction convergence loop
                    counter[i] += 1
                    L *= 1.001
                    yCirc = L*np.sin(thetaCirc) - L*(np.cos(tiltAngle) - np.sin(tiltAngle))
                    zCirc = L*np.cos(thetaCirc) + L*(np.cos(tiltAngle) + np.sin(tiltAngle))
                    yCSi  = np.concatenate([[0],yCirc,[0]])
                    zCSi  = np.concatenate([[0],zCirc,[0]])
                    yCS[i,:] = -yCSi
                    zCS[i,:] = -zCSi

                    # draw circle support
                    xInternalSupportWallCS[i,:],       yInternalSupportWallCS[i,:],       zInternalSupportWallCS[i,:],       \
                    xInternalSupportFilletUpperCS[i,:],yInternalSupportFilletUpperCS[i,:],zInternalSupportFilletUpperCS[i,:],\
                    xInternalSupportFilletLowerCS[i,:],yInternalSupportFilletLowerCS[i,:],zInternalSupportFilletLowerCS[i,:],\
                    supportArea = drawCircleSupportThick(L)

                    nominalArea = (L**2)*(1+0.75*np.pi)
                    usableArea  = nominalArea - supportArea

                    yInternalSupportWallCS[i,:]        += L
                    zInternalSupportWallCS[i,:]        += L
                    yInternalSupportFilletUpperCS[i,:] += L
                    zInternalSupportFilletUpperCS[i,:] += L
                    yInternalSupportFilletLowerCS[i,:] += L
                    zInternalSupportFilletLowerCS[i,:] += L

                charLenDistribution[i] = L

            if self.circlePrintability.lower() == 'thin':

                xInternalSupportWallCS[i,:],       yInternalSupportWallCS[i,:],       zInternalSupportWallCS[i,:],       \
                xInternalSupportFilletUpperCS[i,:],yInternalSupportFilletUpperCS[i,:],zInternalSupportFilletUpperCS[i,:],\
                supportArea = drawCircleSupportThin(L)

                nominalArea = (L**2)*(1+0.75*np.pi)
                usableArea = nominalArea - supportArea
                while usableArea < self.crossSectionalArea[i]:  # area correction convergence loop
                    counter[i] += 1
                    L *= 1.001
                    yCirc = L*np.sin(thetaCirc) - L*(np.cos(tiltAngle) - np.sin(tiltAngle))
                    zCirc = L*np.cos(thetaCirc) + L*(np.cos(tiltAngle) + np.sin(tiltAngle))
                    yCSi  = np.concatenate([[0],yCirc,[0]])
                    zCSi  = np.concatenate([[0],zCirc,[0]])
                    yCS[i,:] = -yCSi
                    zCS[i,:] = -zCSi

                    # draw circle support
                    xInternalSupportWallCS[i,:],       yInternalSupportWallCS[i,:],       zInternalSupportWallCS[i,:],       \
                    xInternalSupportFilletUpperCS[i,:],yInternalSupportFilletUpperCS[i,:],zInternalSupportFilletUpperCS[i,:],\
                    supportArea = drawCircleSupportThin(L)

                    nominalArea = (L**2)*(1+0.75*np.pi)
                    usableArea  = nominalArea - supportArea

                    yInternalSupportWallCS[i,:]        += L
                    zInternalSupportWallCS[i,:]        += L
                    yInternalSupportFilletUpperCS[i,:] += L
                    zInternalSupportFilletUpperCS[i,:] += L

                charLenDistribution[i] = L

        # update values to refelct circle cupport area corrections
        self.crossSectionArea  = (charLenDistribution**2)*(1+0.75*np.pi)
        self.hydraulicDiameter = 4*self.crossSectionalArea / ((1.5*np.pi*charLenDistribution) + (2*charLenDistribution))

        # generate shell
        if self.wallThickness is not None or self.wallHoopStress is not None:
            # A squircle is drawn with its corner on the scroll radius, so its centre, and the bend
            # radius the toroidal correction reads, sits one characteristic length outboard.
            bendRadius = self.voluteScrollRadius + charLenDistribution
            yShellCS, zShellCS, y1p, z1p, wallThickness= dynamicEggShell(yCS,zCS,
                                                        self.wallThickness,
                                                        self.wallHoopStress, self.pressureDifferential, self.hydraulicDiameter,
                                                        bendRadius, self.minWallThickness)
            self.wallThickness = wallThickness
            xShellCS = np.zeros_like(xCS)
            # catch inverted wall
            if abs(np.trapezoid(yShellCS[0,:],zShellCS[0,:])) < abs(np.trapezoid(yCS[0,:],zCS[0,:])):
                self.wallThickness *= -1
                yShellCS, zShellCS, _, _, wallThickness= dynamicEggShell(yCS,zCS,
                                                        self.wallThickness)
            self.wallThickness = abs(wallThickness)

        # move cross sections to correct radius
        if self.alignWallBy == 'inner':
            yCS += self.voluteScrollRadius
            if self.wallThickness is not None:
                yShellCS += self.voluteScrollRadius
            if self.circlePrintability.lower() ==  'thick':
                yInternalSupportWallCS += self.voluteScrollRadius
                yInternalSupportFilletUpperCS += self.voluteScrollRadius
                yInternalSupportFilletLowerCS += self.voluteScrollRadius
            if self.circlePrintability.lower() ==  'thin':
                yInternalSupportWallCS += self.voluteScrollRadius
                yInternalSupportFilletUpperCS += self.voluteScrollRadius
        elif self.alignWallBy == 'outer':

            if self.wallThickness is None:
                print('No outer wall to align by.')
                yCS += self.voluteScrollRadius
                if self.wallThickness is not None:
                    yShellCS += self.voluteScrollRadius
                if self.circlePrintability.lower() ==  'thick':
                    yInternalSupportWallCS += self.voluteScrollRadius
                    yInternalSupportFilletUpperCS += self.voluteScrollRadius
                    yInternalSupportFilletLowerCS += self.voluteScrollRadius
                if self.circlePrintability.lower() ==  'thin':
                    yInternalSupportWallCS += self.voluteScrollRadius
                    yInternalSupportFilletUpperCS += self.voluteScrollRadius
            elif self.wallThickness is not None:
                for i in range(self.numCrossSections):
                    yCS[i,:] -= self.voluteScrollRadius - y1p[i]
                    zCS[i,:] -= -z1p[i]
                    yShellCS[i,:] -= self.voluteScrollRadius - y1p[i]
                    zShellCS[i,:] -= -z1p[i]
                    if self.circlePrintability.lower() ==  'thick':
                        yInternalSupportWallCS[i,:]        -= self.voluteScrollRadius - y1p[i]
                        zInternalSupportWallCS[i,:]        -= -z1p[i]
                        yInternalSupportFilletUpperCS[i,:] -= self.voluteScrollRadius - y1p[i]
                        zInternalSupportFilletUpperCS[i,:] -= -z1p[i]
                        yInternalSupportFilletLowerCS[i,:] -= self.voluteScrollRadius - y1p[i]
                        zInternalSupportFilletLowerCS[i,:] -= -z1p[i]
                    if self.circlePrintability.lower() ==  'thin':
                        yInternalSupportWallCS[i,:]        -= self.voluteScrollRadius - y1p[i]
                        zInternalSupportWallCS[i,:]        -= -z1p[i]
                        yInternalSupportFilletUpperCS[i,:] -= self.voluteScrollRadius - y1p[i]
                        zInternalSupportFilletUpperCS[i,:] -= -z1p[i]
        else:
            raise Exception('Invalid wall alignment argument. Please specify inner or outer.')

        # roll cross sections about scroll axis to create mesh
        sweep = 2*np.pi - self.tongueGap()
        if self.scrollDirection.lower() == 'cw':
            rollAngle = np.linspace(0, sweep, self.numCrossSections)
        elif self.scrollDirection.lower() == 'ccw':
            rollAngle = np.linspace(sweep, 0, self.numCrossSections)
        else:
            raise Exception('Invalid scroll direction argument. Please specify cw or ccw.')
        xVolute, yVolute, zVolute = [np.zeros((self.numCrossSections,self.crossSectionResolution)) for _ in range(3)]
        rollAboutAxis(rollAngle, (xCS, yCS, zCS),
                      (xVolute, yVolute, zVolute))

        # roll outer wall cross sections about scroll axis to create mesh
        if self.wallThickness is not None:
            xShell, yShell, zShell = [np.zeros((self.numCrossSections,self.crossSectionResolution)) for _ in range(3)]
            rollAboutAxis(rollAngle, (xShellCS, yShellCS, zShellCS),
                          (xShell, yShell, zShell))

        # roll inner support cross sections about scroll axis to create mesh
        if self.circlePrintability.lower() == 'thick':
            xInternalSupportWall, yInternalSupportWall, zInternalSupportWall =                      \
                [np.zeros((self.numCrossSections,5)) for _ in range(3)]
            xInternalSupportFilletUpper, yInternalSupportFilletUpper, zInternalSupportFilletUpper = \
                [np.zeros((self.numCrossSections,int(1.5*self.crossSectionResolution+1))) for _ in range(3)]
            xInternalSupportFilletLower, yInternalSupportFilletLower, zInternalSupportFilletLower = \
                [np.zeros((self.numCrossSections,int(0.75*self.crossSectionResolution+2))) for _ in range(3)]
            rollAboutAxis(rollAngle, (xInternalSupportWallCS, yInternalSupportWallCS, zInternalSupportWallCS),
                          (xInternalSupportWall, yInternalSupportWall, zInternalSupportWall))
            rollAboutAxis(rollAngle, (xInternalSupportFilletUpperCS, yInternalSupportFilletUpperCS, zInternalSupportFilletUpperCS),
                          (xInternalSupportFilletUpper, yInternalSupportFilletUpper, zInternalSupportFilletUpper))
            rollAboutAxis(rollAngle, (xInternalSupportFilletLowerCS, yInternalSupportFilletLowerCS, zInternalSupportFilletLowerCS),
                          (xInternalSupportFilletLower, yInternalSupportFilletLower, zInternalSupportFilletLower))
        if self.circlePrintability.lower() == 'thin':
            xInternalSupportWall, yInternalSupportWall, zInternalSupportWall =                      \
                [np.zeros((self.numCrossSections,2)) for _ in range(3)]
            xInternalSupportFilletUpper, yInternalSupportFilletUpper, zInternalSupportFilletUpper = \
                [np.zeros((self.numCrossSections,self.crossSectionResolution)) for _ in range(3)]
            rollAboutAxis(rollAngle, (xInternalSupportWallCS, yInternalSupportWallCS, zInternalSupportWallCS),
                          (xInternalSupportWall, yInternalSupportWall, zInternalSupportWall))
            rollAboutAxis(rollAngle, (xInternalSupportFilletUpperCS, yInternalSupportFilletUpperCS, zInternalSupportFilletUpperCS),
                          (xInternalSupportFilletUpper, yInternalSupportFilletUpper, zInternalSupportFilletUpper))

        # axial location
        zVolute += self.axialOffset
        if self.wallThickness is not None:
            zShell += self.axialOffset
        if self.circlePrintability.lower() == 'thick':
            zInternalSupportWall        += self.axialOffset
            zInternalSupportFilletUpper += self.axialOffset
            zInternalSupportFilletLower += self.axialOffset
        if self.circlePrintability.lower() == 'thin':
            zInternalSupportWall        += self.axialOffset
            zInternalSupportFilletUpper += self.axialOffset

        # assign
        self.xVolute = xVolute
        self.yVolute = yVolute
        self.zVolute = zVolute
        if self.wallThickness is not None:
            self.xShell = xShell
            self.yShell = yShell
            self.zShell = zShell
        if self.circlePrintability.lower() == 'thick':
            self.xInternalSupportWall        = xInternalSupportWall
            self.yInternalSupportWall        = yInternalSupportWall
            self.zInternalSupportWall        = zInternalSupportWall
            self.xInternalSupportFilletUpper = xInternalSupportFilletUpper
            self.yInternalSupportFilletUpper = yInternalSupportFilletUpper
            self.zInternalSupportFilletUpper = zInternalSupportFilletUpper
            self.xInternalSupportFilletLower = xInternalSupportFilletLower
            self.yInternalSupportFilletLower = yInternalSupportFilletLower
            self.zInternalSupportFilletLower = zInternalSupportFilletLower
        if self.circlePrintability.lower() == 'thin':
            self.xInternalSupportWall        = xInternalSupportWall
            self.yInternalSupportWall        = yInternalSupportWall
            self.zInternalSupportWall        = zInternalSupportWall
            self.xInternalSupportFilletUpper = xInternalSupportFilletUpper
            self.yInternalSupportFilletUpper = yInternalSupportFilletUpper
            self.zInternalSupportFilletUpper = zInternalSupportFilletUpper
